'use client';

import React from 'react';
import {
  FileText,
  Image as ImageIcon,
  Minimize2,
  ScanText,
  Binary,
  QrCode,
  Sparkles,
  ShieldCheck,
  Zap,
  ArrowRight,
  Search,
  CheckCircle2,
  Lock,
  ChevronRight,
  PenTool,
  Layers,
  Star,
  Code2,
  Type,
  Fingerprint,
  Combine,
  Split,
  FileImage,
  RotateCw,
  Stamp,
  Hash,
  Tag,
  FileCode,
  Repeat,
  ArrowRightLeft,
  Maximize2,
  FlipHorizontal,
  Table,
  GitCompare,
  ListFilter,
  Scale,
  Activity,
  Percent,
  Clock,
  Palette,
  KeyRound,
  Barcode,
  Brain,
  HardDrive,
  Cpu,
  Sliders,
  Scissors,
  FileStack,
   LucideIcon
} from 'lucide-react';

const ICON_MAP: Record<string, LucideIcon> = {
  Combine: Combine,
  Split: Split,
  Minimize2: Minimize2,
  Minimize: Minimize2,
  FileImage: FileImage,
  Image: ImageIcon,
  RotateCw: RotateCw,
  Stamp: Stamp,
  Hash: Hash,
  Tag: Tag,
  FileText: FileText,
  FileCode: FileCode,
  Repeat: Repeat,
  ArrowRightLeft: ArrowRightLeft,
  Maximize2: Maximize2,
  FlipHorizontal: FlipHorizontal,
  ShieldCheck: ShieldCheck,
  Table: Table,
  Type: Type,
  GitCompare: GitCompare,
  ListFilter: ListFilter,
  Binary: Binary,
  Scale: Scale,
  Activity: Activity,
  Percent: Percent,
  Code2: Code2,
  Clock: Clock,
  Palette: Palette,
  Fingerprint: Fingerprint,
  KeyRound: KeyRound,
  ScanText: ScanText,
  QrCode: QrCode,
  Barcode: Barcode,
  Sparkles: Sparkles,
  Layers: Layers,
  Scissors: Scissors,
  FileStack: FileStack,
  Brain: Brain,
};

interface ToolIconProps {
  name: string;
  className?: string;
}

export function ToolIcon({ name, className = 'w-5 h-5' }: ToolIconProps) {
  const IconComponent = ICON_MAP[name] || FileText;
  return <IconComponent className={className} />;
}
