const fs = require('fs');
const path = require('path');

const ALL_TOOLS = [
  // PART 1: PDF ORGANIZATION (1-25)
  { id: 'pdf-merge', slug: 'merge-pdf', name: 'Merge PDF', category: 'pdf', icon: 'Combine', ext: '.pdf', outExt: 'pdf', desc: 'Combine multiple PDF files into one single organized document.' },
  { id: 'pdf-split', slug: 'split-pdf', name: 'Split PDF', category: 'pdf', icon: 'Split', ext: '.pdf', outExt: 'zip', desc: 'Extract pages or separate a PDF into multiple individual files.' },
  { id: 'pdf-extract-pages', slug: 'extract-pdf-pages', name: 'Extract PDF Pages', category: 'pdf', icon: 'FileCheck', ext: '.pdf', outExt: 'pdf', desc: 'Extract specific page ranges into a new standalone PDF.' },
  { id: 'pdf-delete-pages', slug: 'delete-pdf-pages', name: 'Delete PDF Pages', category: 'pdf', icon: 'Trash2', ext: '.pdf', outExt: 'pdf', desc: 'Remove unwanted or blank pages from your PDF.' },
  { id: 'pdf-reorder-pages', slug: 'reorder-pdf-pages', name: 'Reorder PDF Pages', category: 'pdf', icon: 'Layers', ext: '.pdf', outExt: 'pdf', desc: 'Rearrange and resequence PDF page order.' },
  { id: 'pdf-organizer', slug: 'organize-pdf', name: 'Organize PDF', category: 'pdf', icon: 'Layers', ext: '.pdf', outExt: 'pdf', desc: 'Interactive grid to rotate, delete, and reorder PDF pages.' },
  { id: 'pdf-rotate', slug: 'rotate-pdf', name: 'Rotate PDF', category: 'pdf', icon: 'RotateCw', ext: '.pdf', outExt: 'pdf', desc: 'Rotate PDF pages 90, 180, or 270 degrees.' },
  { id: 'pdf-rotate-single', slug: 'rotate-single-pages', name: 'Rotate Individual Pages', category: 'pdf', icon: 'RotateCcw', ext: '.pdf', outExt: 'pdf', desc: 'Select and rotate specific orientation of individual pages.' },
  { id: 'pdf-reverse-pages', slug: 'reverse-pdf-pages', name: 'Reverse PDF Pages', category: 'pdf', icon: 'Repeat', ext: '.pdf', outExt: 'pdf', desc: 'Invert the entire page order of a PDF document from end to start.' },
  { id: 'pdf-duplicate-pages', slug: 'duplicate-pdf-pages', name: 'Duplicate PDF Pages', category: 'pdf', icon: 'Copy', ext: '.pdf', outExt: 'pdf', desc: 'Duplicate each page in your PDF document multiple times.' },
  { id: 'pdf-insert-pages', slug: 'insert-pdf-pages', name: 'Insert PDF Pages', category: 'pdf', icon: 'FilePlus', ext: '.pdf', outExt: 'pdf', desc: 'Insert blank pages or add pages between existing PDF sheets.' },
  { id: 'pdf-replace-pages', slug: 'replace-pdf-pages', name: 'Replace PDF Pages', category: 'pdf', icon: 'FileText', ext: '.pdf', outExt: 'pdf', desc: 'Replace specific damaged pages with new sheets in a PDF.' },
  { id: 'pdf-extract-selected', slug: 'extract-selected-pages', name: 'Extract Selected Pages', category: 'pdf', icon: 'FileCheck', ext: '.pdf', outExt: 'pdf', desc: 'Pick custom page numbers to create a new PDF.' },
  { id: 'pdf-extract-odd', slug: 'extract-odd-pages', name: 'Extract Odd Pages', category: 'pdf', icon: 'FileText', ext: '.pdf', outExt: 'pdf', desc: 'Extract only odd-numbered pages (1, 3, 5, 7) for duplex printing.' },
  { id: 'pdf-extract-even', slug: 'extract-even-pages', name: 'Extract Even Pages', category: 'pdf', icon: 'FileText', ext: '.pdf', outExt: 'pdf', desc: 'Extract only even-numbered pages (2, 4, 6, 8) for double-sided scans.' },
  { id: 'pdf-remove-blank', slug: 'remove-blank-pages', name: 'Remove Blank PDF Pages', category: 'pdf', icon: 'Trash2', ext: '.pdf', outExt: 'pdf', desc: 'Detect and remove empty blank pages from scanned PDFs.' },
  { id: 'pdf-sort-pages', slug: 'sort-pdf-pages', name: 'Sort PDF Pages', category: 'pdf', icon: 'ArrowUpDown', ext: '.pdf', outExt: 'pdf', desc: 'Sort PDF pages alphabetically or numerically.' },
  { id: 'pdf-page-numbers', slug: 'page-numbering', name: 'PDF Page Numbering', category: 'pdf', icon: 'Binary', ext: '.pdf', outExt: 'pdf', desc: 'Add customizable page numbers to top or bottom of PDF sheets.' },
  { id: 'pdf-add-header', slug: 'add-pdf-header', name: 'Add PDF Header', category: 'pdf', icon: 'FileText', ext: '.pdf', outExt: 'pdf', desc: 'Insert official header titles and reference numbers across all pages.' },
  { id: 'pdf-add-footer', slug: 'add-pdf-footer', name: 'Add PDF Footer', category: 'pdf', icon: 'FileText', ext: '.pdf', outExt: 'pdf', desc: 'Insert copyright notices, page counts, or disclaimer footers.' },
  { id: 'pdf-crop', slug: 'crop-pdf', name: 'PDF Crop', category: 'pdf', icon: 'Crop', ext: '.pdf', outExt: 'pdf', desc: 'Trim margins and crop unwanted white borders from PDF pages.' },
  { id: 'pdf-resize-pages', slug: 'resize-pdf-pages', name: 'PDF Resize Pages', category: 'pdf', icon: 'Scaling', ext: '.pdf', outExt: 'pdf', desc: 'Resize page dimensions to standard A4, Letter, Legal, or A3.' },
  { id: 'pdf-change-size', slug: 'change-pdf-page-size', name: 'PDF Change Page Size', category: 'pdf', icon: 'Scaling', ext: '.pdf', outExt: 'pdf', desc: 'Change PDF dimensions and scale content proportionally.' },
  { id: 'pdf-orientation', slug: 'landscape-portrait-pdf', name: 'PDF Landscape/Portrait Converter', category: 'pdf', icon: 'Maximize2', ext: '.pdf', outExt: 'pdf', desc: 'Convert landscape slides into portrait sheets or vice versa.' },
  { id: 'pdf-booklet', slug: 'pdf-booklet-maker', name: 'PDF Booklet Maker', category: 'pdf', icon: 'BookOpen', ext: '.pdf', outExt: 'pdf', desc: 'Format PDF pages side-by-side for fold-over 2-up booklet printing.' },

  // PART 2: PDF COMPRESSION & OPTIMIZATION (26-40)
  { id: 'pdf-compress', slug: 'compress-pdf', name: 'Compress PDF', category: 'compress', icon: 'Minimize2', ext: '.pdf', outExt: 'pdf', desc: 'Reduce PDF file size while maintaining sharp visual clarity.' },
  { id: 'pdf-extreme-compress', slug: 'extreme-pdf-compression', name: 'Extreme PDF Compression', category: 'compress', icon: 'Minimize2', ext: '.pdf', outExt: 'pdf', desc: 'Maximum compression for strict email attachments and portal limits.' },
  { id: 'pdf-balanced-compress', slug: 'balanced-pdf-compression', name: 'Balanced PDF Compression', category: 'compress', icon: 'Minimize2', ext: '.pdf', outExt: 'pdf', desc: 'Optimal trade-off between compact file size and high resolution.' },
  { id: 'pdf-hq-compress', slug: 'high-quality-pdf-compression', name: 'High Quality PDF Compression', category: 'compress', icon: 'Minimize2', ext: '.pdf', outExt: 'pdf', desc: 'Gentle compression preserving ultra-crisp print quality.' },
  { id: 'pdf-image-compress', slug: 'pdf-image-compression', name: 'PDF Image Compression', category: 'compress', icon: 'Image', ext: '.pdf', outExt: 'pdf', desc: 'Recompress embedded JPEG/PNG photos inside PDFs.' },
  { id: 'pdf-font-opt', slug: 'pdf-font-optimization', name: 'PDF Font Optimization', category: 'compress', icon: 'Type', ext: '.pdf', outExt: 'pdf', desc: 'Subset and compress embedded fonts in PDF files.' },
  { id: 'pdf-metadata-cleaner', slug: 'pdf-metadata-cleaner', name: 'PDF Metadata Cleaner', category: 'security', icon: 'ShieldCheck', ext: '.pdf', outExt: 'pdf', desc: 'Strip hidden author info, revision history, and GPS tracking tags.' },
  { id: 'pdf-size-analyzer', slug: 'pdf-size-analyzer', name: 'PDF Size Analyzer', category: 'calculator', icon: 'BarChart2', ext: '.pdf', outExt: 'txt', desc: 'Inspect how much space images, fonts, and streams consume in a PDF.' },
  { id: 'pdf-optimize', slug: 'pdf-optimization', name: 'PDF Optimization', category: 'compress', icon: 'Zap', ext: '.pdf', outExt: 'pdf', desc: 'Optimize PDF structure for web rendering and rapid downloading.' },
  { id: 'pdf-linearize', slug: 'pdf-fast-web-view', name: 'PDF Fast Web View (Linearize)', category: 'pdf', icon: 'Zap', ext: '.pdf', outExt: 'pdf', desc: 'Reorder PDF streams for instant byte-range streaming in browsers.' },
  { id: 'pdf-remove-objects', slug: 'remove-unused-pdf-objects', name: 'Remove Unused PDF Objects', category: 'compress', icon: 'Trash2', ext: '.pdf', outExt: 'pdf', desc: 'Clean orphan cross-references, hidden metadata, and duplicate objects.' },
  { id: 'pdf-optimize-scan', slug: 'optimize-scanned-pdf', name: 'Optimize Scanned PDF', category: 'ocr', icon: 'ScanText', ext: '.pdf', outExt: 'pdf', desc: 'Clean background noise and compress heavy scanned document pages.' },
  { id: 'pdf-optimize-images', slug: 'optimize-image-heavy-pdf', name: 'Optimize Image-Heavy PDF', category: 'compress', icon: 'Image', ext: '.pdf', outExt: 'pdf', desc: 'Compress high-res graphical manuals and catalogs.' },
  { id: 'pdf-resolution-reducer', slug: 'pdf-resolution-reducer', name: 'PDF Resolution Reducer', category: 'compress', icon: 'Scaling', ext: '.pdf', outExt: 'pdf', desc: 'Downsample high DPI scan images to 150 DPI or 72 DPI.' },
  { id: 'pdf-to-smaller', slug: 'pdf-to-smaller-pdf', name: 'PDF to Smaller PDF', category: 'compress', icon: 'Minimize2', ext: '.pdf', outExt: 'pdf', desc: 'Adaptive size shrinker guaranteed never to make files larger.' },

  // PART 3: PDF CONVERSION (41-64)
  { id: 'pdf-to-docx', slug: 'pdf-to-word', name: 'PDF to Word', category: 'document', icon: 'FileText', ext: '.pdf', outExt: 'docx', desc: 'Convert PDF documents into editable Microsoft Word DOCX files.' },
  { id: 'pdf-to-doc', slug: 'pdf-to-doc-converter', name: 'PDF to DOC', category: 'document', icon: 'FileText', ext: '.pdf', outExt: 'docx', desc: 'Convert PDF files into standard DOC documents.' },
  { id: 'pdf-to-txt', slug: 'pdf-to-txt', name: 'PDF to TXT', category: 'text', icon: 'FileCode', ext: '.pdf', outExt: 'txt', desc: 'Extract clean UTF-8 text from any PDF document.' },
  { id: 'pdf-to-rtf', slug: 'pdf-to-rtf', name: 'PDF to RTF', category: 'document', icon: 'FileText', ext: '.pdf', outExt: 'rtf', desc: 'Export formatted Rich Text with typography and paragraphs.' },
  { id: 'pdf-to-excel', slug: 'pdf-to-excel', name: 'PDF to Excel', category: 'document', icon: 'Table', ext: '.pdf', outExt: 'xlsx', desc: 'Extract data tables and columns from PDF into Excel spreadsheets.' },
  { id: 'pdf-to-xlsx', slug: 'pdf-to-xlsx', name: 'PDF to XLSX', category: 'document', icon: 'Table', ext: '.pdf', outExt: 'xlsx', desc: 'Export structured PDF sheets into XLSX format.' },
  { id: 'pdf-to-csv', slug: 'pdf-to-csv', name: 'PDF to CSV', category: 'document', icon: 'Table', ext: '.pdf', outExt: 'csv', desc: 'Extract structured tabular data from PDF into comma-separated rows.' },
  { id: 'pdf-to-pptx', slug: 'pdf-to-powerpoint', name: 'PDF to PowerPoint', category: 'document', icon: 'Presentation', ext: '.pdf', outExt: 'pptx', desc: 'Convert PDF presentation slides into editable PowerPoint slides.' },
  { id: 'pdf-to-ppt', slug: 'pdf-to-ppt-slides', name: 'PDF to PPT', category: 'document', icon: 'Presentation', ext: '.pdf', outExt: 'pptx', desc: 'Convert PDF pages to PowerPoint slide decks.' },
  { id: 'pdf-to-jpg', slug: 'pdf-to-jpg', name: 'PDF to JPG', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'jpg', desc: 'Convert PDF pages into high-resolution JPG images.' },
  { id: 'pdf-to-jpeg', slug: 'pdf-to-jpeg', name: 'PDF to JPEG', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'jpg', desc: 'Convert PDF pages into standard JPEG files.' },
  { id: 'pdf-to-png', slug: 'pdf-to-png', name: 'PDF to PNG', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'png', desc: 'Convert PDF pages into crisp, transparent-capable PNG images.' },
  { id: 'pdf-to-webp', slug: 'pdf-to-webp', name: 'PDF to WEBP', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'webp', desc: 'Convert PDF pages into lightweight, modern WEBP images.' },
  { id: 'pdf-to-tiff', slug: 'pdf-to-tiff', name: 'PDF to TIFF', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'png', desc: 'Convert PDF sheets into high-depth uncompressed TIFF graphics.' },
  { id: 'pdf-to-bmp', slug: 'pdf-to-bmp', name: 'PDF to BMP', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'jpg', desc: 'Convert PDF pages to lossless Bitmap BMP format.' },
  { id: 'pdf-to-html', slug: 'pdf-to-html', name: 'PDF to HTML', category: 'dev', icon: 'Code', ext: '.pdf', outExt: 'html', desc: 'Convert PDF content and formatting into web-ready HTML code.' },
  { id: 'pdf-to-markdown', slug: 'pdf-to-markdown', name: 'PDF to Markdown', category: 'dev', icon: 'FileCode', ext: '.pdf', outExt: 'md', desc: 'Convert PDF document text and headings into structured Markdown.' },
  { id: 'pdf-to-epub', slug: 'pdf-to-epub', name: 'PDF to EPUB', category: 'document', icon: 'BookOpen', ext: '.pdf', outExt: 'epub', desc: 'Convert PDF documents into readable EPUB eBooks.' },
  { id: 'pdf-to-svg', slug: 'pdf-to-svg', name: 'PDF to SVG', category: 'image', icon: 'Image', ext: '.pdf', outExt: 'svg', desc: 'Export PDF vector graphics and text to SVG format.' },
  { id: 'pdf-to-pdfa', slug: 'pdf-to-pdf-a', name: 'PDF to PDF/A', category: 'pdf', icon: 'ShieldCheck', ext: '.pdf', outExt: 'pdf', desc: 'Convert standard PDF documents into ISO-compliant PDF/A archival.' },
  { id: 'pdf-to-pdfx', slug: 'pdf-to-pdf-x', name: 'PDF to PDF/X', category: 'pdf', icon: 'Printer', ext: '.pdf', outExt: 'pdf', desc: 'Prepare PDF files for high-end professional printing and prepress.' },
  { id: 'pdf-to-grayscale', slug: 'pdf-to-grayscale', name: 'PDF to Grayscale', category: 'pdf', icon: 'Layers', ext: '.pdf', outExt: 'pdf', desc: 'Convert full-color PDF documents into black-and-white / grayscale.' },
  { id: 'pdf-to-bw', slug: 'pdf-to-black-and-white', name: 'PDF to Black & White', category: 'pdf', icon: 'Layers', ext: '.pdf', outExt: 'pdf', desc: 'Convert PDFs to pure binary 1-bit high-contrast black and white.' },
  { id: 'pdf-to-images', slug: 'pdf-to-images-zip', name: 'PDF to Images ZIP', category: 'image', icon: 'Archive', ext: '.pdf', outExt: 'zip', desc: 'Export all PDF pages into a zipped archive of 300 DPI images.' },

  // PART 4: CONVERT TO PDF (65-90)
  { id: 'docx-to-pdf', slug: 'word-to-pdf', name: 'Word to PDF', category: 'document', icon: 'FileText', ext: '.docx,.doc', outExt: 'pdf', desc: 'Convert Microsoft Word DOCX documents into standard PDF files.' },
  { id: 'doc-to-pdf', slug: 'doc-to-pdf', name: 'DOC to PDF', category: 'document', icon: 'FileText', ext: '.doc', outExt: 'pdf', desc: 'Convert legacy DOC files to modern PDF.' },
  { id: 'docx-direct-pdf', slug: 'docx-to-pdf', name: 'DOCX to PDF', category: 'document', icon: 'FileText', ext: '.docx', outExt: 'pdf', desc: 'Convert modern DOCX files to PDF.' },
  { id: 'xlsx-to-pdf', slug: 'excel-to-pdf', name: 'Excel to PDF', category: 'document', icon: 'Table', ext: '.xlsx,.xls', outExt: 'pdf', desc: 'Convert Excel spreadsheets and worksheets into printable PDF tables.' },
  { id: 'xls-to-pdf', slug: 'xls-to-pdf', name: 'XLS to PDF', category: 'document', icon: 'Table', ext: '.xls', outExt: 'pdf', desc: 'Convert legacy XLS spreadsheets to PDF.' },
  { id: 'xlsx-direct-pdf', slug: 'xlsx-to-pdf', name: 'XLSX to PDF', category: 'document', icon: 'Table', ext: '.xlsx', outExt: 'pdf', desc: 'Convert XLSX workbooks into clean PDF tables.' },
  { id: 'csv-to-pdf', slug: 'csv-to-pdf', name: 'CSV to PDF', category: 'document', icon: 'Table', ext: '.csv', outExt: 'pdf', desc: 'Render comma-separated CSV records into clean formatted PDF pages.' },
  { id: 'pptx-to-pdf', slug: 'powerpoint-to-pdf', name: 'PowerPoint to PDF', category: 'document', icon: 'Presentation', ext: '.pptx,.ppt', outExt: 'pdf', desc: 'Convert PowerPoint slide presentations into clean PDF documents.' },
  { id: 'ppt-to-pdf', slug: 'ppt-to-pdf', name: 'PPT to PDF', category: 'document', icon: 'Presentation', ext: '.ppt', outExt: 'pdf', desc: 'Convert legacy PPT presentations to PDF.' },
  { id: 'pptx-direct-pdf', slug: 'pptx-to-pdf', name: 'PPTX to PDF', category: 'document', icon: 'Presentation', ext: '.pptx', outExt: 'pdf', desc: 'Convert modern PPTX slide decks to PDF.' },
  { id: 'txt-to-pdf', slug: 'txt-to-pdf', name: 'TXT to PDF', category: 'text', icon: 'FileText', ext: '.txt', outExt: 'pdf', desc: 'Format and convert plain text files into clean paginated PDF documents.' },
  { id: 'rtf-to-pdf', slug: 'rtf-to-pdf', name: 'RTF to PDF', category: 'document', icon: 'FileText', ext: '.rtf', outExt: 'pdf', desc: 'Convert Rich Text files into styled PDF documents.' },
  { id: 'html-to-pdf', slug: 'html-to-pdf', name: 'HTML to PDF', category: 'dev', icon: 'Code', ext: '.html,.htm', outExt: 'pdf', desc: 'Render HTML files and web layouts into high-resolution PDF pages.' },
  { id: 'markdown-to-pdf', slug: 'markdown-to-pdf', name: 'Markdown to PDF', category: 'dev', icon: 'FileCode', ext: '.md', outExt: 'pdf', desc: 'Convert Markdown documentation into styled PDF reports.' },
  { id: 'jpg-to-pdf', slug: 'jpg-to-pdf', name: 'JPG to PDF', category: 'image', icon: 'Image', ext: '.jpg', outExt: 'pdf', desc: 'Convert JPG photos into a high-quality PDF page.' },
  { id: 'jpeg-to-pdf', slug: 'jpeg-to-pdf', name: 'JPEG to PDF', category: 'image', icon: 'Image', ext: '.jpeg', outExt: 'pdf', desc: 'Convert JPEG images to PDF.' },
  { id: 'png-to-pdf', slug: 'png-to-pdf', name: 'PNG to PDF', category: 'image', icon: 'Image', ext: '.png', outExt: 'pdf', desc: 'Convert transparent PNG graphics into clean PDF sheets.' },
  { id: 'webp-to-pdf', slug: 'webp-to-pdf', name: 'WEBP to PDF', category: 'image', icon: 'Image', ext: '.webp', outExt: 'pdf', desc: 'Convert modern WebP images into universal PDF documents.' },
  { id: 'tiff-to-pdf', slug: 'tiff-to-pdf', name: 'TIFF to PDF', category: 'image', icon: 'Image', ext: '.tiff,.tif', outExt: 'pdf', desc: 'Convert multi-page TIFF scans to PDF.' },
  { id: 'bmp-to-pdf', slug: 'bmp-to-pdf', name: 'BMP to PDF', category: 'image', icon: 'Image', ext: '.bmp', outExt: 'pdf', desc: 'Convert Bitmap BMP images to PDF.' },
  { id: 'svg-to-pdf', slug: 'svg-to-pdf', name: 'SVG to PDF', category: 'image', icon: 'Image', ext: '.svg', outExt: 'pdf', desc: 'Convert scalable SVG vectors into vector PDF pages.' },
  { id: 'epub-to-pdf', slug: 'epub-to-pdf', name: 'EPUB to PDF', category: 'document', icon: 'BookOpen', ext: '.epub', outExt: 'pdf', desc: 'Convert EPUB eBooks into printable PDF books.' },
  { id: 'image-to-pdf', slug: 'images-to-pdf', name: 'Images to PDF', category: 'image', icon: 'Image', ext: '.jpg,.jpeg,.png,.webp,.bmp', outExt: 'pdf', desc: 'Combine single or multiple JPG, PNG, and WebP images into one PDF.' },
  { id: 'multi-images-to-pdf', slug: 'multiple-images-to-pdf', name: 'Multiple Images to PDF', category: 'image', icon: 'Image', ext: '.jpg,.jpeg,.png,.webp,.bmp', outExt: 'pdf', desc: 'Batch bind 50+ photos into a single PDF album.' },
  { id: 'screenshot-to-pdf', slug: 'screenshot-to-pdf', name: 'Screenshot to PDF', category: 'image', icon: 'Monitor', ext: '.png,.jpg,.jpeg', outExt: 'pdf', desc: 'Convert app screenshots into organized PDF reports.' },
  { id: 'webpage-to-pdf', slug: 'webpage-to-pdf', name: 'Webpage to PDF', category: 'dev', icon: 'Globe', ext: '.html,.txt', outExt: 'pdf', desc: 'Convert webpage HTML files into paginated PDF documents.' },

  // PART 5: PDF EDITING (91-117)
  { id: 'pdf-editor', slug: 'edit-pdf', name: 'Edit PDF', category: 'pdf', icon: 'Edit3', ext: '.pdf', outExt: 'pdf', desc: 'Add text, signatures, highlights, drawings, and shapes to PDF documents.' },
  { id: 'pdf-add-text', slug: 'add-text-to-pdf', name: 'Add Text to PDF', category: 'pdf', icon: 'Type', ext: '.pdf', outExt: 'pdf', desc: 'Insert custom text boxes, dates, and form entries into PDF sheets.' },
  { id: 'pdf-add-image', slug: 'add-image-to-pdf', name: 'Add Image to PDF', category: 'pdf', icon: 'Image', ext: '.pdf', outExt: 'pdf', desc: 'Place photos, seals, and logos directly onto PDF pages.' },
  { id: 'pdf-add-shape', slug: 'add-shape-to-pdf', name: 'Add Shape to PDF', category: 'pdf', icon: 'Square', ext: '.pdf', outExt: 'pdf', desc: 'Draw rectangles, circles, lines, and callout shapes on PDF.' },
  { id: 'pdf-draw', slug: 'draw-on-pdf', name: 'Draw on PDF', category: 'pdf', icon: 'PenTool', ext: '.pdf', outExt: 'pdf', desc: 'Freehand sketching, markup pen, and touch drawing on PDF.' },
  { id: 'pdf-highlight', slug: 'highlight-pdf', name: 'Highlight PDF', category: 'pdf', icon: 'Highlighter', ext: '.pdf', outExt: 'pdf', desc: 'Highlight important lines and terms with transparent yellow/green tint.' },
  { id: 'pdf-sign', slug: 'sign-pdf', name: 'Add Signature', category: 'pdf', icon: 'PenTool', ext: '.pdf', outExt: 'pdf', desc: 'Draw, type, or upload electronic signatures to place anywhere on PDFs.' },
  { id: 'pdf-add-stamp', slug: 'add-stamp-to-pdf', name: 'Add Stamp', category: 'pdf', icon: 'Stamp', ext: '.pdf', outExt: 'pdf', desc: 'Insert APPROVED, REJECTED, PAID, and OFFICIAL stamps on documents.' },
  { id: 'pdf-watermark', slug: 'watermark-pdf', name: 'Add Watermark', category: 'pdf', icon: 'Stamp', ext: '.pdf', outExt: 'pdf', desc: 'Add confidential, draft, or custom logo watermarks across all pages.' },
  { id: 'pdf-remove-watermark', slug: 'remove-watermark-pdf', name: 'Remove Watermark', category: 'pdf', icon: 'Trash2', ext: '.pdf', outExt: 'pdf', desc: 'Clean background watermark stamps from PDF documents.' },

  // PART 6: PDF SECURITY & PRIVACY (118-135)
  { id: 'pdf-protect', slug: 'protect-pdf', name: 'Protect PDF with Password', category: 'security', icon: 'Lock', ext: '.pdf', outExt: 'pdf', desc: 'Encrypt PDF files with AES-256 password protection.' },
  { id: 'pdf-encrypt', slug: 'encrypt-pdf', name: 'Encrypt PDF', category: 'security', icon: 'Lock', ext: '.pdf', outExt: 'pdf', desc: 'Strong AES cryptographic protection for confidential documents.' },
  { id: 'pdf-unlock', slug: 'unlock-pdf', name: 'Unlock PDF', category: 'security', icon: 'Unlock', ext: '.pdf', outExt: 'pdf', desc: 'Remove password restrictions and owner locks from authorized PDFs.' },
  { id: 'pdf-remove-password', slug: 'remove-pdf-password', name: 'Remove PDF Password', category: 'security', icon: 'Unlock', ext: '.pdf', outExt: 'pdf', desc: 'Permanently decrypt unlocked PDF files for open sharing.' },
  { id: 'pdf-permissions', slug: 'pdf-permission-manager', name: 'PDF Permission Manager', category: 'security', icon: 'Shield', ext: '.pdf', outExt: 'pdf', desc: 'Set printing, editing, copying, and form filling permissions.' },
  { id: 'pdf-redact', slug: 'redact-pdf', name: 'Redact PDF', category: 'security', icon: 'EyeOff', ext: '.pdf', outExt: 'pdf', desc: 'Permanently blackout confidential text and sensitive figures.' },
  { id: 'pdf-sanitize', slug: 'sanitize-pdf', name: 'Sanitize PDF', category: 'security', icon: 'Shield', ext: '.pdf', outExt: 'pdf', desc: 'Remove embedded scripts, hidden metadata, and attachments.' },

  // PART 7: PDF OCR & SCANNED DOCUMENTS (136-155)
  { id: 'ocr-pdf', slug: 'ocr-pdf', name: 'OCR PDF', category: 'ocr', icon: 'ScanText', ext: '.pdf', outExt: 'docx', desc: 'Make scanned PDF documents searchable and editable in Word.' },
  { id: 'ocr-image', slug: 'ocr-image', name: 'OCR Image', category: 'ocr', icon: 'ScanText', ext: '.jpg,.jpeg,.png,.webp', outExt: 'txt', desc: 'Extract editable text from pictures and photos in 7+ languages.' },
  { id: 'scan-to-pdf', slug: 'scan-to-pdf', name: 'Scan to PDF', category: 'ocr', icon: 'Camera', ext: '.jpg,.png,.jpeg', outExt: 'pdf', desc: 'Capture documents with your device camera and convert to clean PDF.' },
  { id: 'image-searchable-pdf', slug: 'image-to-searchable-pdf', name: 'Image to Searchable PDF', category: 'ocr', icon: 'ScanText', ext: '.jpg,.png,.webp', outExt: 'pdf', desc: 'Turn photo receipts and scans into searchable text-layer PDFs.' },
  { id: 'make-pdf-searchable', slug: 'make-pdf-searchable', name: 'Make PDF Searchable', category: 'ocr', icon: 'Search', ext: '.pdf', outExt: 'pdf', desc: 'Overlay OCR text layer over scanned PDF pages for full-text search.' },
  { id: 'extract-text-pdf', slug: 'extract-text-from-pdf', name: 'Extract Text from PDF', category: 'text', icon: 'FileText', ext: '.pdf', outExt: 'txt', desc: 'Extract pure text from PDF documents instantly.' },
  { id: 'extract-text-image', slug: 'extract-text-from-image', name: 'Extract Text from Image', category: 'ocr', icon: 'ScanText', ext: '.jpg,.png,.jpeg', outExt: 'txt', desc: 'Extract text lines and sentences from photos.' },
  { id: 'ocr-to-word', slug: 'ocr-to-word', name: 'OCR to Word', category: 'ocr', icon: 'FileText', ext: '.pdf,.jpg,.png', outExt: 'docx', desc: 'Convert scanned images and non-selectable PDFs into DOCX.' },
  { id: 'ocr-to-txt', slug: 'ocr-to-txt', name: 'OCR to TXT', category: 'ocr', icon: 'FileCode', ext: '.pdf,.jpg,.png', outExt: 'txt', desc: 'Convert scanned pages into plain TXT text.' },
  { id: 'ocr-to-excel', slug: 'ocr-to-excel', name: 'OCR to Excel', category: 'ocr', icon: 'Table', ext: '.pdf,.jpg,.png', outExt: 'xlsx', desc: 'Extract scanned tabular data into editable Excel sheets.' },
  { id: 'ocr-to-csv', slug: 'ocr-to-csv', name: 'OCR to CSV', category: 'ocr', icon: 'Table', ext: '.pdf,.jpg,.png', outExt: 'csv', desc: 'Extract scanned receipts and tables into CSV format.' },

  // PART 8: WORD / DOC / DOCX TOOLS (156-180)
  { id: 'word-to-txt', slug: 'word-to-txt', name: 'Word to TXT', category: 'document', icon: 'FileText', ext: '.docx,.doc', outExt: 'txt', desc: 'Extract plain text from Word DOCX without formatting.' },
  { id: 'word-to-html', slug: 'word-to-html', name: 'Word to HTML', category: 'document', icon: 'Code', ext: '.docx,.doc', outExt: 'html', desc: 'Convert Word documents into semantic HTML markup.' },
  { id: 'word-to-markdown', slug: 'word-to-markdown', name: 'Word to Markdown', category: 'document', icon: 'FileCode', ext: '.docx,.doc', outExt: 'md', desc: 'Convert Word DOCX documents into clean Markdown.' },
  { id: 'word-counter-doc', slug: 'word-file-analyzer', name: 'Word File Analyzer', category: 'text', icon: 'BarChart2', ext: '.docx,.doc,.txt,.pdf', outExt: 'txt', desc: 'Calculate word count, character count, and reading time.' },
  { id: 'word-meta-cleaner', slug: 'word-metadata-cleaner', name: 'Word Metadata Cleaner', category: 'security', icon: 'ShieldCheck', ext: '.docx', outExt: 'docx', desc: 'Remove tracked changes, author revisions, and comments from Word.' },
  { id: 'word-compressor', slug: 'word-compressor', name: 'Word Compressor', category: 'compress', icon: 'Minimize2', ext: '.docx', outExt: 'docx', desc: 'Compress embedded pictures and strip revision history in Word.' },
  { id: 'word-cleanup', slug: 'word-document-cleanup', name: 'Word Document Cleanup', category: 'document', icon: 'Sparkles', ext: '.docx,.doc', outExt: 'txt', desc: 'Strip bad formatting, double spaces, and hidden tags from Word docs.' },
  { id: 'remove-word-formatting', slug: 'remove-word-formatting', name: 'Remove Word Formatting', category: 'document', icon: 'Eraser', ext: '.docx,.doc', outExt: 'txt', desc: 'Strip all styles, fonts, and colors to get pure clean text.' },
  { id: 'find-replace-word', slug: 'find-replace-in-word', name: 'Find & Replace in Word', category: 'document', icon: 'Search', ext: '.docx,.txt', outExt: 'docx', desc: 'Search and replace names, terms, and values across Word documents.' },

  // PART 9: EXCEL / SPREADSHEET TOOLS (181-200)
  { id: 'xlsx-to-csv', slug: 'xlsx-to-csv', name: 'XLSX to CSV', category: 'document', icon: 'Table', ext: '.xlsx,.xls', outExt: 'csv', desc: 'Convert Excel spreadsheets into comma-separated CSV format.' },
  { id: 'csv-to-xlsx', slug: 'csv-to-xlsx', name: 'CSV to XLSX', category: 'document', icon: 'Table', ext: '.csv', outExt: 'xlsx', desc: 'Convert CSV data files into formatted Microsoft Excel workbooks.' },
  { id: 'excel-to-json', slug: 'excel-to-json', name: 'Excel to JSON', category: 'dev', icon: 'Code', ext: '.xlsx,.xls,.csv', outExt: 'json', desc: 'Convert Excel spreadsheet records into structured JSON objects.' },
  { id: 'json-to-excel', slug: 'json-to-excel', name: 'JSON to Excel', category: 'dev', icon: 'Table', ext: '.json', outExt: 'xlsx', desc: 'Convert JSON array objects into a downloadable Excel spreadsheet.' },
  { id: 'excel-to-txt', slug: 'excel-to-txt', name: 'Excel to TXT', category: 'document', icon: 'FileText', ext: '.xlsx,.xls', outExt: 'txt', desc: 'Export Excel sheet rows as tab-delimited text.' },
  { id: 'excel-to-html', slug: 'excel-to-html', name: 'Excel to HTML', category: 'dev', icon: 'Code', ext: '.xlsx,.xls', outExt: 'html', desc: 'Convert Excel workbooks into interactive HTML table pages.' },
  { id: 'csv-cleaner', slug: 'csv-cleaner', name: 'CSV Cleaner', category: 'document', icon: 'Filter', ext: '.csv', outExt: 'csv', desc: 'Remove blank lines, duplicate rows, and invalid CSV records.' },
  { id: 'csv-formatter', slug: 'csv-formatter', name: 'CSV Formatter', category: 'document', icon: 'Table', ext: '.csv', outExt: 'csv', desc: 'Align columns, trim white spaces, and standardize delimiters.' },
  { id: 'csv-deduplicator', slug: 'csv-deduplicator', name: 'CSV Deduplicator', category: 'document', icon: 'Filter', ext: '.csv', outExt: 'csv', desc: 'Find and purge identical duplicated rows from large CSV files.' },

  // PART 10: POWERPOINT TOOLS (201-212)
  { id: 'pptx-to-txt', slug: 'pptx-to-text', name: 'PPTX to Text', category: 'document', icon: 'Presentation', ext: '.pptx,.ppt', outExt: 'txt', desc: 'Extract all slide speeches, headings, and notes into plain text.' },
  { id: 'ppt-to-images', slug: 'ppt-to-images', name: 'PPT to Images', category: 'document', icon: 'Image', ext: '.pptx,.ppt', outExt: 'zip', desc: 'Convert slides into image slides in a ZIP file.' },
  { id: 'ppt-slide-counter', slug: 'ppt-slide-counter', name: 'PPT Slide Counter', category: 'document', icon: 'BarChart2', ext: '.pptx,.ppt', outExt: 'txt', desc: 'Count total slides, speaker notes, and shapes in PowerPoint.' },

  // PART 11: IMAGE TOOLS (213-252)
  { id: 'image-compress', slug: 'image-compressor', name: 'Image Compressor', category: 'compress', icon: 'Minimize2', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Shrink image file size with adaptive WebP / JPEG compression.' },
  { id: 'jpg-compressor', slug: 'jpg-compressor', name: 'JPG Compressor', category: 'compress', icon: 'Minimize2', ext: '.jpg,.jpeg', outExt: 'jpg', desc: 'Compress JPG photos for quick web and email delivery.' },
  { id: 'png-compressor', slug: 'png-compressor', name: 'PNG Compressor', category: 'compress', icon: 'Minimize2', ext: '.png', outExt: 'png', desc: 'Lossless compression for transparent PNG graphics.' },
  { id: 'webp-compressor', slug: 'webp-compressor', name: 'WEBP Compressor', category: 'compress', icon: 'Minimize2', ext: '.webp', outExt: 'webp', desc: 'Shrink WebP files to minimum byte footprint.' },
  { id: 'image-resizer', slug: 'image-resizer', name: 'Image Resizer', category: 'image', icon: 'Scaling', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Resize dimensions and compress to exact KB limits (e.g. under 50KB).' },
  { id: 'image-cropper', slug: 'image-cropper', name: 'Image Cropper', category: 'image', icon: 'Crop', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Crop pictures to 1:1 square, 16:9 widescreen, 4:3, or custom ratios.' },
  { id: 'image-rotator', slug: 'image-rotator', name: 'Image Rotator', category: 'image', icon: 'RotateCw', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Rotate photos 90, 180, 270 degrees or custom degree angles.' },
  { id: 'image-flipper', slug: 'image-flipper', name: 'Image Flipper', category: 'image', icon: 'FlipHorizontal', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Flip images horizontally (mirror) or vertically.' },
  { id: 'image-converter', slug: 'image-converter', name: 'Image Converter', category: 'image', icon: 'Image', ext: '.jpg,.jpeg,.png,.webp,.bmp,.tiff', outExt: 'png', desc: 'Universal image format conversion studio.' },
  { id: 'jpg-to-png', slug: 'jpg-to-png', name: 'JPG to PNG', category: 'image', icon: 'Image', ext: '.jpg,.jpeg', outExt: 'png', desc: 'Convert JPEG images to high-fidelity PNG format.' },
  { id: 'png-to-jpg', slug: 'png-to-jpg', name: 'PNG to JPG', category: 'image', icon: 'Image', ext: '.png', outExt: 'jpg', desc: 'Convert PNG graphics into lightweight compressed JPG images.' },
  { id: 'jpg-to-webp', slug: 'jpg-to-webp', name: 'JPG to WEBP', category: 'image', icon: 'Image', ext: '.jpg,.jpeg', outExt: 'webp', desc: 'Convert JPG to modern lightweight WebP.' },
  { id: 'png-to-webp', slug: 'png-to-webp', name: 'PNG to WEBP', category: 'image', icon: 'Image', ext: '.png', outExt: 'webp', desc: 'Convert PNG with transparency to WebP.' },
  { id: 'webp-to-jpg', slug: 'webp-to-jpg', name: 'WEBP to JPG', category: 'image', icon: 'Image', ext: '.webp', outExt: 'jpg', desc: 'Convert WebP images back into universally compatible JPGs.' },
  { id: 'webp-to-png', slug: 'webp-to-png', name: 'WEBP to PNG', category: 'image', icon: 'Image', ext: '.webp', outExt: 'png', desc: 'Convert WebP images to lossless PNG format.' },
  { id: 'tiff-to-jpg', slug: 'tiff-to-jpg', name: 'TIFF to JPG', category: 'image', icon: 'Image', ext: '.tiff,.tif', outExt: 'jpg', desc: 'Convert high-depth TIFF scans to JPG.' },
  { id: 'bmp-to-jpg', slug: 'bmp-to-jpg', name: 'BMP to JPG', category: 'image', icon: 'Image', ext: '.bmp', outExt: 'jpg', desc: 'Convert uncompressed Bitmap BMP images to compact JPG.' },
  { id: 'heic-to-jpg', slug: 'heic-to-jpg', name: 'HEIC to JPG', category: 'image', icon: 'Image', ext: '.heic,.heif', outExt: 'jpg', desc: 'Convert Apple iPhone HEIC/HEIF photos to universally readable JPG.' },
  { id: 'heic-to-png', slug: 'heic-to-png', name: 'HEIC to PNG', category: 'image', icon: 'Image', ext: '.heic,.heif', outExt: 'png', desc: 'Convert iPhone HEIC photos to lossless PNG.' },
  { id: 'passport-photo-maker', slug: 'passport-photo-maker', name: 'Passport Photo Studio', category: 'image', icon: 'Camera', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Create official 3.5x4.5cm passport photos with white background and print sheets.' },
  { id: 'background-remover', slug: 'background-remover', name: 'AI Background Remover', category: 'image', icon: 'Sparkles', ext: '.jpg,.jpeg,.png,.webp', outExt: 'png', desc: 'Remove image backgrounds locally with AI smart cutout.' },
  { id: 'image-grayscale', slug: 'grayscale-image', name: 'Grayscale Image', category: 'image', icon: 'Layers', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Convert color photos into artistic monochrome.' },
  { id: 'image-bw', slug: 'black-and-white-image', name: 'Black & White Image', category: 'image', icon: 'Layers', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Convert pictures into high-contrast B&W.' },
  { id: 'image-sharpen', slug: 'image-sharpen', name: 'Image Sharpen', category: 'image', icon: 'Sun', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Enhance edge details and sharpness in blurry photos.' },
  { id: 'image-blur', slug: 'image-blur', name: 'Image Blur', category: 'image', icon: 'Sun', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Apply Gaussian blur effect to soften pictures or mask backgrounds.' },
  { id: 'image-brightness', slug: 'image-brightness-adjuster', name: 'Image Brightness Adjuster', category: 'image', icon: 'Sun', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Brighten dark underexposed photos or tone down overexposed images.' },
  { id: 'image-contrast', slug: 'image-contrast-adjuster', name: 'Image Contrast Adjuster', category: 'image', icon: 'Sun', ext: '.jpg,.jpeg,.png,.webp', outExt: 'jpg', desc: 'Adjust color dynamic range and contrast pop.' },
  { id: 'image-palette', slug: 'image-palette', name: 'Image Color Palette Extractor', category: 'image', icon: 'Palette', ext: '.jpg,.jpeg,.png,.webp', outExt: 'txt', desc: 'Extract dominant HEX color swatches and CSS palettes from images.' },
  { id: 'image-zip-creator', slug: 'image-zip-creator', name: 'Image ZIP Creator', category: 'image', icon: 'Archive', ext: '.jpg,.jpeg,.png,.webp', outExt: 'zip', desc: 'Pack multiple images into a zipped download file.' },

  // PART 12: TEXT TOOLS (253-290)
  { id: 'word-counter', slug: 'word-counter', name: 'Word Counter', category: 'text', icon: 'Type', ext: '.txt,.md,.doc,.docx', outExt: 'txt', desc: 'Real-time word count, character count, sentence count, and reading time.' },
  { id: 'char-counter', slug: 'character-counter', name: 'Character Counter', category: 'text', icon: 'Type', ext: '.txt', outExt: 'txt', desc: 'Count total characters including and excluding spaces.' },
  { id: 'sentence-counter', slug: 'sentence-counter', name: 'Sentence Counter', category: 'text', icon: 'Type', ext: '.txt', outExt: 'txt', desc: 'Calculate sentences and grammatical paragraph count.' },
  { id: 'reading-time-calc', slug: 'reading-time-calculator', name: 'Reading Time Calculator', category: 'text', icon: 'Clock', ext: '.txt', outExt: 'txt', desc: 'Estimate silent reading and speaking presentation duration.' },
  { id: 'case-converter', slug: 'case-converter', name: 'Text Case Converter', category: 'text', icon: 'Type', ext: '.txt', outExt: 'txt', desc: 'Convert text to UPPERCASE, lowercase, Title Case, and Sentence case.' },
  { id: 'uppercase-converter', slug: 'uppercase-converter', name: 'UPPERCASE Converter', category: 'text', icon: 'Type', ext: '.txt', outExt: 'txt', desc: 'Convert all letters to CAPITAL UPPERCASE.' },
  { id: 'lowercase-converter', slug: 'lowercase-converter', name: 'lowercase Converter', category: 'text', icon: 'Type', ext: '.txt', outExt: 'txt', desc: 'Convert all letters to small lowercase.' },
  { id: 'title-case-converter', slug: 'title-case-converter', name: 'Title Case Converter', category: 'text', icon: 'Type', ext: '.txt', outExt: 'txt', desc: 'Capitalize Major Words For Book Titles and Headers.' },
  { id: 'remove-extra-spaces', slug: 'remove-extra-spaces', name: 'Remove Extra Spaces', category: 'text', icon: 'Eraser', ext: '.txt', outExt: 'txt', desc: 'Clean duplicate spaces, trailing whitespace, and tab indents.' },
  { id: 'remove-blank-lines', slug: 'remove-blank-lines', name: 'Remove Blank Lines', category: 'text', icon: 'Eraser', ext: '.txt', outExt: 'txt', desc: 'Strip empty lines and carriage returns from text.' },
  { id: 'duplicate-remover', slug: 'remove-duplicate-lines', name: 'Remove Duplicate Lines', category: 'text', icon: 'Filter', ext: '.txt', outExt: 'txt', desc: 'Deduplicate, sort A-Z, and strip blank lines from text files.' },
  { id: 'sort-lines-az', slug: 'sort-lines-a-z', name: 'Sort Lines A-Z', category: 'text', icon: 'ArrowUpDown', ext: '.txt', outExt: 'txt', desc: 'Sort list items in alphabetical ascending order.' },
  { id: 'sort-lines-za', slug: 'sort-lines-z-a', name: 'Sort Lines Z-A', category: 'text', icon: 'ArrowUpDown', ext: '.txt', outExt: 'txt', desc: 'Sort list items in reverse alphabetical order.' },
  { id: 'reverse-text', slug: 'reverse-text', name: 'Reverse Text', category: 'text', icon: 'Repeat', ext: '.txt', outExt: 'txt', desc: 'Reverse entire text characters backwards.' },
  { id: 'reverse-lines', slug: 'reverse-lines', name: 'Reverse Lines', category: 'text', icon: 'Repeat', ext: '.txt', outExt: 'txt', desc: 'Invert the order of lines from bottom to top.' },
  { id: 'text-diff', slug: 'text-diff-viewer', name: 'Text Diff / Compare', category: 'text', icon: 'GitCompare', ext: '.txt,.json,.js,.py', outExt: 'txt', desc: 'Side-by-side visual diff comparison highlighting added and deleted words.' },
  { id: 'find-replace-text', slug: 'find-and-replace-text', name: 'Find & Replace', category: 'text', icon: 'Search', ext: '.txt', outExt: 'txt', desc: 'Fast global find and replace with regex support.' },
  { id: 'extract-emails', slug: 'extract-emails', name: 'Extract Emails', category: 'text', icon: 'Mail', ext: '.txt', outExt: 'txt', desc: 'Extract all email addresses from raw text data.' },
  { id: 'extract-urls', slug: 'extract-urls', name: 'Extract URLs', category: 'text', icon: 'Globe', ext: '.txt', outExt: 'txt', desc: 'Extract all web links and HTTP URLs from documents.' },
  { id: 'extract-phones', slug: 'extract-phone-numbers', name: 'Extract Phone Numbers', category: 'text', icon: 'Phone', ext: '.txt', outExt: 'txt', desc: 'Extract valid international phone and mobile numbers.' },
  { id: 'extract-numbers', slug: 'extract-numbers', name: 'Extract Numbers', category: 'text', icon: 'Binary', ext: '.txt', outExt: 'txt', desc: 'Extract all integer and decimal numbers.' },
  { id: 'extract-hashtags', slug: 'extract-hashtags', name: 'Extract Hashtags', category: 'text', icon: 'Hash', ext: '.txt', outExt: 'txt', desc: 'Extract social media hashtags from posts and captions.' },
  { id: 'extract-mentions', slug: 'extract-mentions', name: 'Extract Mentions', category: 'text', icon: 'AtSign', ext: '.txt', outExt: 'txt', desc: 'Extract @username handles from social feeds.' },
  { id: 'text-to-docx-alt', slug: 'text-to-word', name: 'Text to Word', category: 'text', icon: 'FileText', ext: '.txt', outExt: 'docx', desc: 'Convert plain text notes into styled Microsoft Word DOCX.' },
  { id: 'markdown-editor', slug: 'markdown-editor', name: 'Live Markdown to PDF Studio', category: 'dev', icon: 'FileCode', ext: '.md,.txt', outExt: 'pdf', desc: 'Write Markdown with real-time preview and export formatted PDF.' },
  { id: 'markdown-to-html', slug: 'markdown-to-html', name: 'Markdown to HTML', category: 'dev', icon: 'Code', ext: '.md', outExt: 'html', desc: 'Parse Markdown into clean semantic HTML.' },
  { id: 'html-to-text', slug: 'html-to-text', name: 'HTML to Text', category: 'dev', icon: 'FileText', ext: '.html', outExt: 'txt', desc: 'Strip HTML tags to get pure readable text.' },
  { id: 'lorem-ipsum-gen', slug: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', category: 'text', icon: 'FileText', ext: '.txt', outExt: 'txt', desc: 'Generate placeholder dummy text paragraphs and sentences.' },

  // PART 13: GENERAL FILE TOOLS (291-310)
  { id: 'zip-creator', slug: 'zip-file-creator', name: 'ZIP Creator', category: 'document', icon: 'Archive', ext: '*/*', outExt: 'zip', desc: 'Compress multiple documents and images into a single ZIP file.' },
  { id: 'zip-extractor', slug: 'zip-file-extractor', name: 'ZIP Extractor', category: 'document', icon: 'FolderArchive', ext: '.zip', outExt: 'zip', desc: 'Unzip and unpack archives directly inside your browser memory.' },
  { id: 'file-size-analyzer', slug: 'file-size-analyzer', name: 'File Size Analyzer', category: 'calculator', icon: 'BarChart2', ext: '*/*', outExt: 'txt', desc: 'Inspect exact byte weights and breakdown of file contents.' },
  { id: 'file-hash-generator', slug: 'file-hash-generator', name: 'File Hash Generator', category: 'security', icon: 'Fingerprint', ext: '*/*', outExt: 'txt', desc: 'Calculate SHA-256, SHA-512, and SHA-1 cryptographic hashes.' },
  { id: 'md5-generator', slug: 'md5-checksum-generator', name: 'MD5 Generator', category: 'security', icon: 'Fingerprint', ext: '*/*', outExt: 'txt', desc: 'Calculate MD5 checksums to verify file integrity.' },
  { id: 'sha256-generator', slug: 'sha-256-generator', name: 'SHA-256 Generator', category: 'security', icon: 'Fingerprint', ext: '*/*', outExt: 'txt', desc: 'Generate cryptographic SHA-256 signatures.' },
  { id: 'base64-converter', slug: 'base64-converter', name: 'Base64 Encoder & Decoder', category: 'dev', icon: 'Binary', ext: '*/*', outExt: 'txt', desc: 'Encode files and text to Base64 strings or decode back to files.' },
  { id: 'password-generator', slug: 'password-generator', name: 'Password Generator', category: 'security', icon: 'Key', ext: '.txt', outExt: 'txt', desc: 'Generate high-entropy randomized cryptographic passwords.' },

  // PART 14 & 15: PRODUCTIVITY TOOLS & CALCULATORS (311-350)
  { id: 'qr-generator', slug: 'qr-code-generator', name: 'QR Code Generator', category: 'qr', icon: 'QrCode', ext: '.txt', outExt: 'png', desc: 'Generate custom styled QR codes with colors, icons, and logos.' },
  { id: 'barcode-generator', slug: 'barcode-generator', name: 'Barcode Generator', category: 'qr', icon: 'Barcode', ext: '.txt', outExt: 'png', desc: 'Generate CODE128, EAN-13, and UPC barcodes for products.' },
  { id: 'url-encoder-decoder', slug: 'url-encoder-decoder', name: 'URL Encoder / Decoder', category: 'dev', icon: 'Globe', ext: '.txt', outExt: 'txt', desc: 'Encode URI components (%20) and decode web query strings.' },
  { id: 'json-formatter', slug: 'json-formatter', name: 'JSON Formatter', category: 'dev', icon: 'Code2', ext: '.json,.txt', outExt: 'json', desc: 'Prettify, minify, and validate JSON data structures with syntax tree.' },
  { id: 'json-validator', slug: 'json-validator', name: 'JSON Validator', category: 'dev', icon: 'CheckCircle', ext: '.json,.txt', outExt: 'json', desc: 'Validate syntax errors in JSON objects with line locations.' },
  { id: 'uuid-generator', slug: 'uuid-generator', name: 'UUID Generator', category: 'dev', icon: 'Cpu', ext: '.txt', outExt: 'txt', desc: 'Generate bulk RFC4122 compliant v4 UUIDs and GUIDs instantly.' },
  { id: 'color-converter', slug: 'color-converter', name: 'Color Converter', category: 'dev', icon: 'Palette', ext: '.txt', outExt: 'txt', desc: 'Convert between HEX, RGB, HSL, and CMYK color representations.' },
  { id: 'timestamp-converter', slug: 'timestamp-converter', name: 'Timestamp Converter', category: 'dev', icon: 'Clock', ext: '.txt', outExt: 'txt', desc: 'Convert Epoch timestamps to human-readable dates across timezones.' },
  { id: 'general-unit-converter', slug: 'general-unit-converter', name: 'Unit Converter', category: 'calculator', icon: 'Sliders', ext: '.txt', outExt: 'txt', desc: 'Convert length, mass, temperature, speed, area, and volume units.' },
  { id: 'file-size-converter', slug: 'storage-unit-converter', name: 'File Size Converter', category: 'calculator', icon: 'HardDrive', ext: '.txt', outExt: 'txt', desc: 'Convert bytes, KB, MB, GB, TB, and petabytes seamlessly.' },
  { id: 'math-calculators', slug: 'percentage-calculator', name: 'Percentage Calculator', category: 'calculator', icon: 'Percent', ext: '.txt', outExt: 'txt', desc: 'Calculate percentage increases, discounts, tips, and loan margins.' },
  { id: 'bandwidth-calculator', slug: 'bandwidth-calculator', name: 'Bandwidth ETA Calculator', category: 'calculator', icon: 'Wifi', ext: '.txt', outExt: 'txt', desc: 'Calculate accurate file download and transfer time based on speed.' },
  { id: 'dpi-calculator', slug: 'dpi-aspect-ratio-calculator', name: 'DPI & Aspect Ratio Calculator', category: 'calculator', icon: 'Monitor', ext: '.txt', outExt: 'txt', desc: 'Calculate print resolutions, pixel dimensions, and 16:9 / 4:3 ratios.' },
  { id: 'media-downloader', slug: 'media-downloader', name: 'Social Media Video Downloader', category: 'media', icon: 'Video', ext: '.txt', outExt: 'mp4', desc: 'Download 4K videos from YouTube, Instagram, TikTok, and WhatsApp.' },
  { id: 'video-to-mp3', slug: 'video-to-mp3', name: 'Video to MP3', category: 'media', icon: 'Music', ext: '.mp4,.mov,.avi,.mkv,.webm', outExt: 'mp3', desc: 'Extract crystal-clear studio audio from video files in your browser.' },
  { id: 'audio-booster', slug: 'audio-volume-booster', name: 'Audio Volume Booster', category: 'media', icon: 'Volume2', ext: '.mp3,.wav,.m4a,.aac', outExt: 'wav', desc: 'Amplify quiet MP3, WAV, and lecture audio recordings up to 300%.' },
  { id: 'audio-cutter', slug: 'audio-cutter', name: 'Audio Cutter', category: 'media', icon: 'Scissors', ext: '.mp3,.wav,.ogg,.m4a', outExt: 'mp3', desc: 'Trim and cut audio tracks with visual waveform selection.' },
  { id: 'audio-speed', slug: 'audio-speed', name: 'Audio Speed Changer', category: 'media', icon: 'FastForward', ext: '.mp3,.wav,.m4a', outExt: 'wav', desc: 'Speed up or slow down MP3 and WAV playback from 0.5x to 2.5x.' },
];

console.log('Total verified tools:', ALL_TOOLS.length);

const code = `import { ToolDefinition, ToolCategory } from './types';

export const TOOLS_LIST: ToolDefinition[] = ${JSON.stringify(ALL_TOOLS.map(t => ({
  id: t.id,
  slug: t.slug,
  name: t.name,
  shortDesc: t.desc,
  fullDesc: t.desc,
  category: t.category,
  icon: t.icon,
  popular: true,
  featured: true,
  isClientSide: true,
  acceptedMimeTypes: t.ext.includes('pdf') ? ['application/pdf'] : t.ext.includes('docx') ? ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'] : t.ext.includes('xlsx') ? ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'] : t.ext.includes('csv') ? ['text/csv'] : t.ext.includes('jpg') ? ['image/jpeg', 'image/png', 'image/webp'] : t.ext.includes('png') ? ['image/png', 'image/jpeg'] : t.ext.includes('txt') ? ['text/plain'] : t.ext.includes('json') ? ['application/json'] : ['*/*'],
  acceptedExtensions: t.ext.split(',').map(e => e.trim()),
  maxFiles: t.id.includes('merge') || t.id.includes('zip') || t.id.includes('multi') ? 50 : 10,
  maxFileSizeMB: 500,
  outputExtension: t.outExt,
  outputMimeType: t.outExt === 'pdf' ? 'application/pdf' : t.outExt === 'docx' ? 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' : t.outExt === 'xlsx' ? 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' : t.outExt === 'csv' ? 'text/csv' : t.outExt === 'jpg' ? 'image/jpeg' : t.outExt === 'png' ? 'image/png' : t.outExt === 'zip' ? 'application/zip' : t.outExt === 'json' ? 'application/json' : 'text/plain',
  tags: [t.name.toLowerCase(), t.category, t.slug.replace(/-/g, ' ')],
})), null, 2)};

export const CATEGORIES_CONFIG: { id: ToolCategory; label: string; icon: string; desc: string }[] = [
  { id: 'pdf', label: 'PDF Tools', icon: 'FileText', desc: 'Merge, split, compress, edit, secure and convert PDF documents.' },
  { id: 'document', label: 'Document & Office', icon: 'FileCheck', desc: 'Convert Word, Excel, CSV, PowerPoint, and Markdown files.' },
  { id: 'image', label: 'Image Studio', icon: 'Image', desc: 'Convert, compress, crop, resize, and optimize pictures.' },
  { id: 'ocr', label: 'OCR & Scans', icon: 'ScanText', desc: 'Extract text from scanned PDFs and photos.' },
  { id: 'text', label: 'Text & Writing', icon: 'Type', desc: 'Word count, case converters, line sorters, and diff checker.' },
  { id: 'compress', label: 'Compression', icon: 'Minimize2', desc: 'Reduce file sizes of PDFs, images, and documents.' },
  { id: 'security', label: 'Security & Privacy', icon: 'Fingerprint', desc: 'SHA checksums, password protect, sanitize, and redact.' },
  { id: 'media', label: 'Audio & Video', icon: 'Video', desc: '4K video downloader, MP3 converter, and volume booster.' },
  { id: 'calculator', label: 'Calculators & Units', icon: 'Binary', desc: 'Storage units, bandwidth ETA, general units, and percentages.' },
  { id: 'dev', label: 'Developer Utilities', icon: 'Code2', desc: 'JSON formatter, Base64, timestamps, colors, and UUIDs.' },
  { id: 'qr', label: 'QR & Barcodes', icon: 'QrCode', desc: 'Generate styled QR codes and inventory barcodes.' },
  { id: 'ai', label: 'AI Workspace', icon: 'Sparkles', desc: 'AI document summarizer, rewriter, and workflow builder.' },
];
`;

fs.writeFileSync(path.join(__dirname, 'lib', 'tools-config.ts'), code, 'utf-8');
console.log('Done generating tools-config.ts!');
