import { ToolDefinition, ToolCategory } from './types';

export const TOOLS_LIST: ToolDefinition[] = [
  // ==================== 1. PDF TOOLS ====================
  {
    id: 'pdf-merge',
    slug: 'merge-pdf',
    name: 'Merge PDF',
    shortDesc: 'Combine multiple PDF files into one single organized document.',
    fullDesc: 'Merge multiple PDF documents together in any order you choose. Fast, secure, and preserves fonts and visual styling.',
    category: 'pdf',
    icon: 'Combine',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 50,
    maxFileSizeMB: 100,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    tags: ['merge', 'combine', 'join', 'pdf', 'pdf merge', 'bind pdf'],
    faq: [
      { question: 'Will the original formatting and fonts be preserved?', answer: 'Yes, pages and font tables are preserved with 100% fidelity.' },
      { question: 'Is my data secure?', answer: 'Files are processed locally in your browser memory via WebAssembly and never uploaded.' },
    ],
  },
  {
    id: 'pdf-split',
    slug: 'split-pdf',
    name: 'Split PDF',
    shortDesc: 'Extract pages or separate a PDF into multiple individual files.',
    fullDesc: 'Split a large PDF file into separate single-page documents or select custom page ranges to extract.',
    category: 'pdf',
    icon: 'Split',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 1,
    maxFileSizeMB: 100,
    outputExtension: 'zip',
    outputMimeType: 'application/zip',
    options: [
      {
        id: 'splitMode',
        label: 'Split Mode',
        type: 'select',
        defaultValue: 'all',
        options: [
          { label: 'Split into single pages', value: 'all' },
          { label: 'Extract custom page range', value: 'range' },
        ],
      },
      {
        id: 'pageRange',
        label: 'Page Range (e.g. 1-3, 5, 7-9)',
        type: 'text',
        defaultValue: '1-2',
        placeholder: 'e.g. 1-3, 5',
      },
    ],
    tags: ['split', 'extract', 'separate', 'pages', 'pdf split'],
  },
  {
    id: 'pdf-compress',
    slug: 'compress-pdf',
    name: 'Compress PDF',
    shortDesc: 'Reduce PDF file size while maintaining sharp visual clarity.',
    fullDesc: 'Optimize and shrink the size of your PDF files for email attachments, web publishing, and storage reduction.',
    category: 'compress',
    icon: 'Minimize2',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 20,
    maxFileSizeMB: 150,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      {
        id: 'targetSizeLimit',
        label: 'Target Size Requirement (KB / MB Limit)',
        type: 'select',
        defaultValue: 'auto',
        options: [
          { label: 'Auto Adaptive (Optimal Balance)', value: 'auto' },
          { label: 'Under 100 KB (Govt Job & Exam Portals)', value: '100kb' },
          { label: 'Under 200 KB (Passport / KYC Uploads)', value: '200kb' },
          { label: 'Under 500 KB (Standard Web Portals)', value: '500kb' },
          { label: 'Under 1 MB (Email Standard)', value: '1mb' },
          { label: 'Under 2 MB (Max 2MB Official Upload Limit)', value: '2mb' },
          { label: 'Under 5 MB (High Res Archival)', value: '5mb' },
        ],
      },
      {
        id: 'level',
        label: 'Compression Level & Quality',
        type: 'select',
        defaultValue: 'medium',
        options: [
          { label: 'Extreme (~75% size reduction - Smallest File)', value: 'extreme' },
          { label: 'Recommended (~55% size reduction - Good Quality)', value: 'medium' },
          { label: 'Light (~30% size reduction - Maximum Clarity)', value: 'light' },
        ],
      },
    ],
    tags: ['compress', 'shrink', 'reduce size', 'optimize', 'pdf compress', 'compress pdf to mb', 'reduce pdf size'],
  },
  {
    id: 'image-to-pdf',
    slug: 'image-to-pdf',
    name: 'Image to PDF',
    shortDesc: 'Convert JPG, PNG, WebP, and BMP images into a clean PDF document.',
    fullDesc: 'Convert single or multiple pictures into a standard PDF with custom orientation, margins, and layout.',
    category: 'pdf',
    icon: 'FileImage',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/bmp', 'image/gif'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.bmp', '.gif'],
    maxFiles: 50,
    maxFileSizeMB: 50,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      {
        id: 'orientation',
        label: 'Page Orientation',
        type: 'select',
        defaultValue: 'auto',
        options: [
          { label: 'Auto (Fit Image)', value: 'auto' },
          { label: 'Portrait (A4)', value: 'portrait' },
          { label: 'Landscape (A4)', value: 'landscape' },
        ],
      },
      {
        id: 'margin',
        label: 'Page Margin',
        type: 'select',
        defaultValue: 'small',
        options: [
          { label: 'No Margin', value: 'none' },
          { label: 'Small Margin', value: 'small' },
          { label: 'Big Margin', value: 'big' },
        ],
      },
    ],
    tags: ['jpg to pdf', 'png to pdf', 'webp to pdf', 'photos to pdf', 'images to pdf'],
  },
  {
    id: 'pdf-to-image',
    slug: 'pdf-to-jpg',
    name: 'PDF to Image (JPG/PNG)',
    shortDesc: 'Convert PDF pages into high-resolution JPG, PNG or WebP images.',
    fullDesc: 'Extract every page of a PDF document into standalone picture files. Download pages individually or packed in a single ZIP.',
    category: 'pdf',
    icon: 'Image',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 5,
    maxFileSizeMB: 50,
    outputExtension: 'zip',
    outputMimeType: 'application/zip',
    options: [
      {
        id: 'format',
        label: 'Image Format',
        type: 'select',
        defaultValue: 'image/jpeg',
        options: [
          { label: 'JPG (Best for photos & small size)', value: 'image/jpeg' },
          { label: 'PNG (Lossless, sharp text)', value: 'image/png' },
          { label: 'WebP (Modern, high efficiency)', value: 'image/webp' },
        ],
      },
    ],
    tags: ['pdf to jpg', 'pdf to png', 'pdf to image', 'export pdf pages'],
  },
  {
    id: 'pdf-rotate',
    slug: 'rotate-pdf',
    name: 'Rotate PDF Pages',
    shortDesc: 'Rotate PDF pages 90°, 180°, or 270° clockwise or counter-clockwise.',
    fullDesc: 'Fix upside-down or sideways pages in your PDF document permanently with one click.',
    category: 'pdf',
    icon: 'RotateCw',
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 10,
    maxFileSizeMB: 100,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      {
        id: 'angle',
        label: 'Rotation Angle',
        type: 'select',
        defaultValue: '90',
        options: [
          { label: '90° Clockwise', value: '90' },
          { label: '180° Upside Down', value: '180' },
          { label: '270° Counter-Clockwise', value: '270' },
        ],
      },
    ],
    tags: ['rotate', 'turn', 'orientation', 'pdf rotate'],
  },
  {
    id: 'pdf-watermark',
    slug: 'watermark-pdf',
    name: 'Add PDF Watermark',
    shortDesc: 'Overlay copyright, confidential, or brand stamps across PDF pages.',
    fullDesc: 'Protect your intellectual property by embedding custom text watermarks with customizable opacity, angle, and position.',
    category: 'pdf',
    icon: 'Stamp',
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 10,
    maxFileSizeMB: 50,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      { id: 'text', label: 'Watermark Text', type: 'text', defaultValue: 'CONFIDENTIAL', placeholder: 'e.g. CONFIDENTIAL, DRAFT' },
      { id: 'opacity', label: 'Opacity (0.1 - 1.0)', type: 'slider', defaultValue: 0.3, min: 0.1, max: 1.0, step: 0.05 },
      { id: 'color', label: 'Text Color', type: 'color', defaultValue: '#ff0000' },
    ],
    tags: ['watermark', 'stamp', 'confidential', 'branding', 'pdf watermark'],
  },
  {
    id: 'pdf-page-numbers',
    slug: 'add-page-numbers-pdf',
    name: 'Add Page Numbers',
    shortDesc: 'Insert numbered headers or footers with customizable formatting.',
    fullDesc: 'Add elegant page numbering (e.g. "Page 1 of 10", "1/10", or simple numbers) to any position on your PDF.',
    category: 'pdf',
    icon: 'Hash',
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 10,
    maxFileSizeMB: 50,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      {
        id: 'position',
        label: 'Position',
        type: 'select',
        defaultValue: 'bottom-center',
        options: [
          { label: 'Bottom Center', value: 'bottom-center' },
          { label: 'Bottom Right', value: 'bottom-right' },
          { label: 'Bottom Left', value: 'bottom-left' },
          { label: 'Top Right', value: 'top-right' },
        ],
      },
      {
        id: 'format',
        label: 'Format Style',
        type: 'select',
        defaultValue: 'Page {n} of {total}',
        options: [
          { label: 'Page 1 of 10', value: 'Page {n} of {total}' },
          { label: '1 / 10', value: '{n} / {total}' },
          { label: 'Page 1', value: 'Page {n}' },
          { label: '1', value: '{n}' },
        ],
      },
    ],
    tags: ['page numbers', 'footer', 'header', 'pagination', 'number pdf'],
  },
  {
    id: 'pdf-metadata',
    slug: 'edit-pdf-metadata',
    name: 'Edit PDF Metadata',
    shortDesc: 'View and update Title, Author, Subject, and Keywords in your PDF.',
    fullDesc: 'Clean or update document properties and metadata tags for SEO and document indexing.',
    category: 'pdf',
    icon: 'Tag',
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 1,
    maxFileSizeMB: 50,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      { id: 'title', label: 'Document Title', type: 'text', defaultValue: '', placeholder: 'e.g. Annual Financial Report' },
      { id: 'author', label: 'Author Name', type: 'text', defaultValue: '', placeholder: 'e.g. John Doe' },
      { id: 'subject', label: 'Subject', type: 'text', defaultValue: '', placeholder: 'e.g. Business Summary' },
      { id: 'keywords', label: 'Keywords (comma-separated)', type: 'text', defaultValue: '', placeholder: 'e.g. report, 2026, finance' },
    ],
    tags: ['metadata', 'author', 'title', 'properties', 'pdf info'],
  },
  {
    id: 'text-to-pdf',
    slug: 'text-to-pdf',
    name: 'Text & TXT to PDF',
    shortDesc: 'Convert plain text, notes, and TXT files into clean formatted PDF documents.',
    fullDesc: 'Type or paste plain text or upload .txt files to generate elegant, paginated PDF documents with custom typography.',
    category: 'pdf',
    icon: 'FileText',
    isClientSide: true,
    acceptedMimeTypes: ['text/plain'],
    acceptedExtensions: ['.txt', '.log'],
    maxFiles: 5,
    maxFileSizeMB: 10,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    options: [
      {
        id: 'fontSize',
        label: 'Font Size',
        type: 'select',
        defaultValue: '12',
        options: [
          { label: '10 pt (Compact)', value: '10' },
          { label: '12 pt (Standard)', value: '12' },
          { label: '14 pt (Large)', value: '14' },
        ],
      },
    ],
    tags: ['txt to pdf', 'text to pdf', 'notes to pdf', 'convert text'],
  },
  {
    id: 'markdown-to-pdf',
    slug: 'markdown-to-pdf',
    name: 'Markdown to PDF',
    shortDesc: 'Convert Markdown (.md) documents with headers, tables, and code to PDF.',
    fullDesc: 'Renders GitHub Flavored Markdown into beautiful, professionally styled PDF pages.',
    category: 'pdf',
    icon: 'FileCode',
    isClientSide: true,
    acceptedMimeTypes: ['text/markdown', 'text/plain'],
    acceptedExtensions: ['.md', '.markdown'],
    maxFiles: 5,
    maxFileSizeMB: 10,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    tags: ['md to pdf', 'markdown to pdf', 'readme to pdf'],
  },

  // ==================== 2. IMAGE TOOLS ====================
  {
    id: 'image-converter',
    slug: 'image-converter',
    name: 'Universal Image Converter',
    shortDesc: 'Convert pictures between JPG, PNG, WebP, SVG, and BMP instantly.',
    fullDesc: 'High-speed image format converter. Converts single images or bulk batches with zero quality degradation.',
    category: 'image',
    icon: 'Repeat',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml', 'image/bmp', 'image/gif'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.svg', '.bmp', '.gif'],
    maxFiles: 50,
    maxFileSizeMB: 50,
    outputExtension: 'png',
    outputMimeType: 'image/png',
    options: [
      {
        id: 'targetFormat',
        label: 'Convert To',
        type: 'select',
        defaultValue: 'image/png',
        options: [
          { label: 'PNG (Lossless & transparent)', value: 'image/png' },
          { label: 'JPG (Smallest file size)', value: 'image/jpeg' },
          { label: 'WebP (Next-gen modern web)', value: 'image/webp' },
        ],
      },
    ],
    tags: ['jpg to png', 'png to jpg', 'webp to png', 'png to webp', 'convert image'],
  },
  {
    id: 'jpg-to-png',
    slug: 'jpg-to-png',
    name: 'JPG to PNG',
    shortDesc: 'Convert JPEG photos to lossless PNG format.',
    fullDesc: 'Convert JPG images to PNG format to support transparent background workflows and lossless editing.',
    category: 'image',
    icon: 'ArrowRightLeft',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg'],
    acceptedExtensions: ['.jpg', '.jpeg'],
    maxFiles: 30,
    maxFileSizeMB: 30,
    outputExtension: 'png',
    outputMimeType: 'image/png',
    tags: ['jpg to png', 'jpeg to png', 'convert jpg'],
  },
  {
    id: 'png-to-jpg',
    slug: 'png-to-jpg',
    name: 'PNG to JPG',
    shortDesc: 'Convert heavy PNG graphics to lightweight JPG photos.',
    fullDesc: 'Reduce file sizes dramatically by converting PNG graphics into compressed JPG images with solid background.',
    category: 'image',
    icon: 'ArrowRightLeft',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/png'],
    acceptedExtensions: ['.png'],
    maxFiles: 30,
    maxFileSizeMB: 30,
    outputExtension: 'jpg',
    outputMimeType: 'image/jpeg',
    tags: ['png to jpg', 'png to jpeg', 'compress png to jpg'],
  },
  {
    id: 'image-compressor',
    slug: 'image-compressor',
    name: 'Image Compressor',
    shortDesc: 'Compress JPG, PNG, and WebP images up to 80% with minimal visual loss.',
    fullDesc: 'Smart lossy and lossless image compressor. See live before/after size comparisons and download optimized files.',
    category: 'compress',
    icon: 'Minimize',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
    maxFiles: 50,
    maxFileSizeMB: 50,
    outputExtension: 'jpg',
    outputMimeType: 'image/jpeg',
    options: [
      {
        id: 'targetSizeLimit',
        label: 'Target Size Requirement (KB / MB Limit)',
        type: 'select',
        defaultValue: 'auto',
        options: [
          { label: 'Auto Adaptive (Optimal Balance)', value: 'auto' },
          { label: 'Under 50 KB (Passport Photo & Signature)', value: '50kb' },
          { label: 'Under 100 KB (Govt Job & Exam Portals)', value: '100kb' },
          { label: 'Under 200 KB (Web Portal Uploads)', value: '200kb' },
          { label: 'Under 500 KB (KYC & Documents)', value: '500kb' },
          { label: 'Under 1 MB (Web & Email Images)', value: '1mb' },
          { label: 'Under 2 MB (Max 2MB Official Upload Limit)', value: '2mb' },
        ],
      },
      {
        id: 'quality',
        label: 'Compression Strength & Quality',
        type: 'select',
        defaultValue: '0.75',
        options: [
          { label: 'Medium (Balanced - recommended)', value: '0.75' },
          { label: 'High (Smallest file size)', value: '0.5' },
          { label: 'Low (Maximum clarity)', value: '0.9' },
        ],
      },
    ],
    tags: ['compress image', 'shrink photo', 'reduce image size', 'optimize image'],
  },
  {
    id: 'image-resizer',
    slug: 'image-resizer',
    name: 'Image Resizer',
    shortDesc: 'Resize photos by exact pixel dimensions or percentage ratio.',
    fullDesc: 'Change image width and height smoothly. Maintain aspect ratio or stretch to custom dimensions.',
    category: 'image',
    icon: 'Maximize2',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/bmp'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.bmp'],
    maxFiles: 20,
    maxFileSizeMB: 40,
    outputExtension: 'png',
    outputMimeType: 'image/png',
    options: [
      { id: 'width', label: 'Width (px)', type: 'number', defaultValue: 1200 },
      { id: 'height', label: 'Height (px)', type: 'number', defaultValue: 800 },
      { id: 'maintainAspect', label: 'Maintain Aspect Ratio', type: 'checkbox', defaultValue: true },
    ],
    tags: ['resize', 'dimensions', 'width', 'height', 'scale photo'],
  },
  {
    id: 'image-rotate-flip',
    slug: 'rotate-image',
    name: 'Rotate & Flip Image',
    shortDesc: 'Rotate photos 90°/180° and flip horizontally or vertically.',
    fullDesc: 'Easily mirror or reorient your pictures with real-time visual preview.',
    category: 'image',
    icon: 'FlipHorizontal',
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
    maxFiles: 10,
    maxFileSizeMB: 30,
    outputExtension: 'png',
    outputMimeType: 'image/png',
    options: [
      {
        id: 'action',
        label: 'Transformation',
        type: 'select',
        defaultValue: 'rotate-90',
        options: [
          { label: 'Rotate 90° Clockwise', value: 'rotate-90' },
          { label: 'Rotate 180°', value: 'rotate-180' },
          { label: 'Rotate 270° (90° CCW)', value: 'rotate-270' },
          { label: 'Flip Horizontal (Mirror)', value: 'flip-h' },
          { label: 'Flip Vertical', value: 'flip-v' },
        ],
      },
    ],
    tags: ['rotate image', 'flip photo', 'mirror image'],
  },
  {
    id: 'image-exif',
    slug: 'image-metadata',
    name: 'Image Metadata & EXIF Stripper',
    shortDesc: 'Inspect and remove camera, GPS, and timestamp EXIF tags for privacy.',
    fullDesc: 'Protect your privacy by sanitizing all hidden location and device metadata before sharing photos online.',
    category: 'image',
    icon: 'ShieldCheck',
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp'],
    maxFiles: 10,
    maxFileSizeMB: 30,
    outputExtension: 'jpg',
    outputMimeType: 'image/jpeg',
    tags: ['exif', 'metadata', 'gps remove', 'privacy', 'strip metadata'],
  },

  // ==================== 3. DOCUMENT TOOLS ====================
  {
    id: 'pdf-to-docx',
    slug: 'pdf-to-word',
    name: 'PDF to Word (DOCX)',
    shortDesc: 'Convert PDF documents into editable Microsoft Word (.docx) files.',
    fullDesc: 'Extracts text, headings, and formatting from PDF files and converts them into native, fully editable Word (.docx) documents 100% in your browser.',
    category: 'document',
    icon: 'FileText',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 10,
    maxFileSizeMB: 50,
    outputExtension: 'docx',
    outputMimeType: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
    tags: ['pdf to word', 'pdf to docx', 'convert pdf to word', 'pdf convert', 'pdf word'],
    faq: [
      { question: 'Will the Word document be editable?', answer: 'Yes! The resulting .docx file contains fully editable text, headings, and paragraphs compatible with Microsoft Word and Google Docs.' },
      { question: 'Is my document private?', answer: 'Yes, your file is processed entirely in your browser memory and never uploaded to any server.' },
    ],
  },
  {
    id: 'docx-to-pdf',
    slug: 'word-to-pdf',
    name: 'Word (DOCX) to PDF',
    shortDesc: 'Convert Microsoft Word (.docx) documents into clean PDF files.',
    fullDesc: 'Parses Word documents client-side using mammoth engine and compiles them into clean, paginated PDF format.',
    category: 'document',
    icon: 'FileText',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.wordprocessingml.document'],
    acceptedExtensions: ['.docx'],
    maxFiles: 5,
    maxFileSizeMB: 25,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    tags: ['word to pdf', 'docx to pdf', 'doc to pdf'],
  },
  {
    id: 'excel-to-pdf',
    slug: 'excel-to-pdf',
    name: 'Excel (XLSX/CSV) to PDF',
    shortDesc: 'Convert Excel spreadsheets and CSV data sheets into formatted PDF tables.',
    fullDesc: 'Turns spreadsheet worksheets and tabular CSV files into clean, readable PDF tables with headers and row borders.',
    category: 'document',
    icon: 'Table',
    isClientSide: true,
    acceptedMimeTypes: ['application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', 'text/csv', 'application/vnd.ms-excel'],
    acceptedExtensions: ['.xlsx', '.xls', '.csv'],
    maxFiles: 5,
    maxFileSizeMB: 20,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    tags: ['excel to pdf', 'xlsx to pdf', 'csv to pdf', 'spreadsheet to pdf'],
  },

  // ==================== 4. TEXT & WRITING TOOLS ====================
  {
    id: 'word-counter',
    slug: 'word-counter',
    name: 'Word & Character Counter',
    shortDesc: 'Real-time word, character, sentence, paragraph, and reading time counter.',
    fullDesc: 'Analyze your text in real time with detailed statistics on character counts with and without spaces, reading duration, and speaking pace.',
    category: 'text',
    icon: 'FileText',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['word counter', 'character count', 'reading time', 'text statistics', 'wordcount'],
  },
  {
    id: 'case-converter',
    slug: 'case-converter',
    name: 'Case Converter',
    shortDesc: 'Convert text between UPPERCASE, lowercase, Title Case, camelCase, snake_case, and kebab-case.',
    fullDesc: 'Transform text formatting instantly across 8 standard programming and writing case styles.',
    category: 'text',
    icon: 'Type',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['case converter', 'uppercase', 'lowercase', 'title case', 'camelcase', 'snake_case'],
  },
  {
    id: 'text-diff',
    slug: 'text-compare',
    name: 'Text Compare & Diff Checker',
    shortDesc: 'Compare two text blocks side-by-side and highlight additions, deletions, and differences.',
    fullDesc: 'Find differences between two versions of code, contracts, or text snippets with visual line highlighting.',
    category: 'text',
    icon: 'GitCompare',
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['text diff', 'compare text', 'diff checker', 'text comparison'],
  },
  {
    id: 'duplicate-remover',
    slug: 'remove-duplicate-lines',
    name: 'Remove Duplicate Lines',
    shortDesc: 'Deduplicate text lines and clean up lists with one click.',
    fullDesc: 'Clean lists, CSV columns, and logs by stripping repeated entries while preserving natural order.',
    category: 'text',
    icon: 'ListFilter',
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['remove duplicates', 'dedupe lines', 'clean list', 'unique lines'],
  },

  // ==================== 5. CALCULATORS & CONVERTERS ====================
  {
    id: 'file-size-converter',
    slug: 'mb-to-kb',
    name: 'File Size & Storage Unit Converter',
    shortDesc: 'Convert Bytes, KB, MB, GB, TB, PB (Decimal 1000 & Binary 1024 KiB/MiB).',
    fullDesc: 'Instant bidirectional digital storage unit converter with interactive slider, step-by-step formula breakdown, and memory reference tables.',
    category: 'calculator',
    icon: 'Binary',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['bytes to kb', 'kb to mb', 'mb to gb', 'gb to tb', 'kib mib gib', 'storage calculator'],
  },
  {
    id: 'general-unit-converter',
    slug: 'unit-converter',
    name: 'Universal Unit Converter',
    shortDesc: 'Convert Length, Weight, Temperature, Area, Volume, Speed, Time, and Pressure.',
    fullDesc: 'Comprehensive conversion suite supporting Metric, Imperial, and Scientific measurement units with instant calculation.',
    category: 'calculator',
    icon: 'Scale',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['unit converter', 'length', 'weight', 'temperature', 'inches to cm', 'lbs to kg'],
  },
  {
    id: 'bandwidth-calculator',
    slug: 'download-time-calculator',
    name: 'Download & Upload Time Calculator',
    shortDesc: 'Estimate file transfer duration based on file size and internet connection speed.',
    fullDesc: 'Calculate exactly how long it takes to download or upload games, 4K videos, backups, and large files over 4G, 5G, Fiber, or custom bandwidth.',
    category: 'calculator',
    icon: 'Activity',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['download time', 'upload time', 'transfer speed', 'bandwidth calculator', 'mbps to mb/s'],
  },
  {
    id: 'math-calculators',
    slug: 'percentage-calculator',
    name: 'Percentage & Ratio Calculator',
    shortDesc: 'Compute percentages, proportion ratios, averages, and date/age differences.',
    fullDesc: 'Solve percentage increase/decrease, fractions, proportions, and date elapsed durations with clean formulas.',
    category: 'calculator',
    icon: 'Percent',
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['percentage calculator', 'ratio', 'average', 'age calculator', 'date math'],
  },

  // ==================== 6. DEVELOPER & WEB UTILITIES ====================
  {
    id: 'json-formatter',
    slug: 'json-formatter',
    name: 'JSON Formatter & Validator',
    shortDesc: 'Format, validate, beautify, and minify JSON strings with instant syntax error detection.',
    fullDesc: 'Format nested JSON structures, fix indentation, validate RFC 8259 syntax, and copy clean or minified output.',
    category: 'dev',
    icon: 'Code2',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['json formatter', 'json validator', 'beautify json', 'minify json', 'json lint'],
  },
  {
    id: 'base64-converter',
    slug: 'base64-encode-decode',
    name: 'Base64 Encoder & Decoder',
    shortDesc: 'Encode and decode plain text, UTF-8 strings, and file data into Base64 format.',
    fullDesc: 'Convert text or upload binary images/files to generate clean Base64 data URIs and strings.',
    category: 'dev',
    icon: 'FileCode',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['base64', 'base64 encode', 'base64 decode', 'data uri'],
  },
  {
    id: 'timestamp-converter',
    slug: 'unix-timestamp-converter',
    name: 'Unix Timestamp Converter',
    shortDesc: 'Convert Unix Epoch seconds and milliseconds to UTC, ISO, and Local date/time.',
    fullDesc: 'Interactive epoch converter with live real-time timestamp clock, relative time calculation, and timezone parsing.',
    category: 'dev',
    icon: 'Clock',
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['unix timestamp', 'epoch converter', 'time converter', 'iso date'],
  },
  {
    id: 'color-converter',
    slug: 'color-converter',
    name: 'Color Converter & Palette Studio',
    shortDesc: 'Convert colors between HEX, RGB, HSL, CMYK, and CSS variables.',
    fullDesc: 'Inspect color codes, pick palette hues, and convert color models with live visual swatch preview.',
    category: 'dev',
    icon: 'Palette',
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['hex to rgb', 'rgb to hex', 'hsl converter', 'cmyk', 'color picker'],
  },

  // ==================== 7. SECURITY & CRYPTOGRAPHY ====================
  {
    id: 'hash-generator',
    slug: 'hash-generator',
    name: 'Hash Generator & File Checksum',
    shortDesc: 'Generate SHA-256, SHA-512, and SHA-1 hashes for text strings and local files.',
    fullDesc: 'Compute cryptographically secure cryptographic hash digests using browser Web Crypto API. Verify file integrity and checksums.',
    category: 'security',
    icon: 'Fingerprint',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['sha256', 'sha512', 'hash generator', 'file checksum', 'crypto hash'],
  },
  {
    id: 'password-generator',
    slug: 'password-generator',
    name: 'Password Generator & Strength Meter',
    shortDesc: 'Generate cryptographically strong passwords and test entropy security.',
    fullDesc: 'Create secure passwords with customizable length, character sets, and crack-time entropy estimations.',
    category: 'security',
    icon: 'KeyRound',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: '',
    outputMimeType: '',
    tags: ['password generator', 'password strength', 'entropy', 'random password', 'uuid generator'],
  },

  // ==================== 8. OCR TOOLS ====================
  {
    id: 'ocr-image-to-text',
    slug: 'ocr-image-to-text',
    name: 'OCR Image to Text',
    shortDesc: 'Extract text from scanned documents, receipts, photos, and screenshots.',
    fullDesc: 'Optical Character Recognition powered by client-side Web Workers. Supports English, Arabic, Urdu, Hindi, Spanish, French and German with one-click copy and text export.',
    category: 'ocr',
    icon: 'ScanText',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/bmp'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.bmp'],
    maxFiles: 5,
    maxFileSizeMB: 20,
    outputExtension: 'txt',
    outputMimeType: 'text/plain',
    tags: ['ocr', 'image to text', 'extract text', 'arabic ocr', 'urdu ocr', 'hindi ocr', 'receipt scanner'],
  },

  // ==================== 9. QR & BARCODE TOOLS ====================
  {
    id: 'qr-generator',
    slug: 'qr-code-generator',
    name: 'QR Code Generator',
    shortDesc: 'Generate custom styled QR codes for URLs, Wi-Fi, vCard contacts, emails, and text.',
    fullDesc: 'Create high-resolution QR codes with customizable colors, background transparency, and margin sizes. Download in PNG format.',
    category: 'qr',
    icon: 'QrCode',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'png',
    outputMimeType: 'image/png',
    tags: ['qr code', 'make qr', 'wifi qr', 'vcard qr', 'barcode'],
  },
  {
    id: 'barcode-generator',
    slug: 'barcode-generator',
    name: 'Barcode Generator',
    shortDesc: 'Create Code128, EAN-13, UPC-A, and Code39 barcodes for products and inventory.',
    fullDesc: 'Generate professional, scan-compliant barcodes for retail, shipping labels, and inventory systems. Export crisp PNG images.',
    category: 'qr',
    icon: 'Barcode',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'png',
    outputMimeType: 'image/png',
    tags: ['barcode', 'code128', 'ean13', 'upc', 'inventory barcode'],
  },

  // ==================== 11. SOCIAL MEDIA & VIDEO DOWNLOADER TOOLS ====================
  {
    id: 'media-downloader',
    slug: 'video-downloader',
    name: 'Social Media Video & Audio Downloader',
    shortDesc: 'Download 4K / 1080p videos & MP3 audio from YouTube, Instagram, Facebook, TikTok & X.',
    fullDesc: 'Universal multi-platform media extractor. Paste any link to download high-resolution MP4 video streams, extract 320kbps MP3 audio, or save HD thumbnails with zero watermarks.',
    category: 'media',
    icon: 'Video',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'mp4',
    outputMimeType: 'video/mp4',
    tags: ['video downloader', 'youtube downloader', 'instagram reel download', 'facebook video', 'tiktok download', 'mp3 extractor', 'save video'],
  },
  {
    id: 'youtube-downloader',
    slug: 'youtube-downloader',
    name: 'YouTube 4K & MP3 Downloader',
    shortDesc: 'Extract YouTube Shorts, full videos in 4K/1080p and high-bitrate MP3 audio.',
    fullDesc: 'Save YouTube videos in ultra-high resolution or convert any video to 320kbps studio MP3 audio with one click.',
    category: 'media',
    icon: 'Youtube',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'mp4',
    outputMimeType: 'video/mp4',
    tags: ['youtube', 'youtube mp3', 'youtube 4k', 'yt shorts download'],
  },
  {
    id: 'instagram-downloader',
    slug: 'instagram-downloader',
    name: 'Instagram Reels & Video Saver',
    shortDesc: 'Download Instagram Reels, video posts, and IGTV clips in original HD quality.',
    fullDesc: 'Save your favorite Instagram Reels and videos directly to your device without quality loss.',
    category: 'media',
    icon: 'Instagram',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'mp4',
    outputMimeType: 'video/mp4',
    tags: ['instagram reel', 'ig download', 'instagram video', 'insta reels'],
  },
  {
    id: 'tiktok-downloader',
    slug: 'tiktok-downloader',
    name: 'TikTok Video Downloader (No Watermark)',
    shortDesc: 'Save viral TikTok videos in crystal-clear Full HD without any watermark logo.',
    fullDesc: 'Clean TikTok video saver. Download TikTok clips and sounds in crisp MP4 and MP3 format.',
    category: 'media',
    icon: 'Music',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'mp4',
    outputMimeType: 'video/mp4',
    tags: ['tiktok without watermark', 'tiktok mp4', 'tiktok sound', 'tik tok saver'],
  },
  {
    id: 'whatsapp-status-saver',
    slug: 'whatsapp-status-saver',
    name: 'WhatsApp Status & Media Saver',
    shortDesc: 'Save WhatsApp status videos, photos, and voice notes before they disappear.',
    fullDesc: 'Easily preserve high-quality WhatsApp status updates, voice notes, and shared video clips.',
    category: 'media',
    icon: 'MessageCircle',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'mp4',
    outputMimeType: 'video/mp4',
    tags: ['whatsapp status', 'status saver', 'whatsapp video download', 'wa status'],
  },
  {
    id: 'video-to-mp3',
    slug: 'video-to-mp3',
    name: 'Video to Audio (MP3/WAV)',
    shortDesc: 'Extract crystal-clear MP3 & WAV audio tracks from any video file.',
    fullDesc: 'Extracts full uncompressed audio from MP4, WebM, MOV, and AVI videos up to 500 MB directly in your browser.',
    category: 'media',
    icon: 'Music',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['video/mp4', 'video/webm', 'video/quicktime', 'video/x-matroska', 'video/avi'],
    acceptedExtensions: ['.mp4', '.webm', '.mov', '.mkv', '.avi'],
    maxFiles: 10,
    maxFileSizeMB: 500,
    outputExtension: 'wav',
    outputMimeType: 'audio/wav',
    tags: ['video to mp3', 'extract audio', 'video to audio', 'mp4 to mp3', 'sound extractor'],
  },
  {
    id: 'favicon-generator',
    slug: 'favicon-generator',
    name: 'Favicon & Web Icon Pack',
    shortDesc: 'Generate 16x16, 32x32, 48x48, 180x180, and 512x512 icons + HTML code.',
    fullDesc: 'Upload your brand logo and generate complete, ready-to-deploy favicon packages with webmanifest and HTML tags.',
    category: 'image',
    icon: 'Layers',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/png', 'image/jpeg', 'image/svg+xml', 'image/webp'],
    acceptedExtensions: ['.png', '.jpg', '.jpeg', '.svg', '.webp'],
    maxFiles: 5,
    maxFileSizeMB: 150,
    outputExtension: 'zip',
    outputMimeType: 'application/zip',
    tags: ['favicon generator', 'icon maker', 'apple touch icon', 'web icon', 'ico generator'],
  },
  {
    id: 'jwt-decoder',
    slug: 'jwt-decoder',
    name: 'JWT Token Inspector & Decoder',
    shortDesc: 'Decode JSON Web Token headers, payloads, claims, and expiry dates.',
    fullDesc: 'Inspect and debug JWT authentication tokens safely in browser without exposing secret keys.',
    category: 'dev',
    icon: 'KeyRound',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'json',
    outputMimeType: 'application/json',
    tags: ['jwt decoder', 'jwt inspector', 'token parser', 'json web token'],
  },
  {
    id: 'uuid-generator',
    slug: 'uuid-generator',
    name: 'UUID / GUID Generator (v4)',
    shortDesc: 'Bulk generate cryptographically secure Version-4 Unique Identifiers.',
    fullDesc: 'Create randomized, unique GUIDs and UUIDs with customizable casing, count, and hyphen formatting.',
    category: 'dev',
    icon: 'Fingerprint',
    popular: true,
    isClientSide: true,
    acceptedMimeTypes: [],
    acceptedExtensions: [],
    maxFiles: 0,
    maxFileSizeMB: 0,
    outputExtension: 'txt',
    outputMimeType: 'text/plain',
    tags: ['uuid generator', 'guid generator', 'uuid v4', 'random id'],
  },
  {
    id: 'audio-cutter',
    slug: 'audio-cutter',
    name: 'Audio Cutter & Ringtone Trimmer',
    shortDesc: 'Trim, cut, and slice MP3, WAV, and audio tracks with millisecond accuracy.',
    fullDesc: 'Upload any music or audio file up to 500 MB, choose start and end times, and export clean trimmed audio instantly.',
    category: 'media',
    icon: 'Scissors',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['audio/mpeg', 'audio/wav', 'audio/aac', 'audio/ogg', 'audio/x-m4a', 'audio/flac'],
    acceptedExtensions: ['.mp3', '.wav', '.aac', '.ogg', '.m4a', '.flac'],
    maxFiles: 5,
    maxFileSizeMB: 500,
    outputExtension: 'wav',
    outputMimeType: 'audio/wav',
    tags: ['audio cutter', 'mp3 trimmer', 'cut audio', 'ringtone maker', 'audio slice'],
  },
  {
    id: 'audio-booster',
    slug: 'audio-booster',
    name: 'Audio Volume Booster',
    shortDesc: 'Boost and amplify quiet MP3, WAV, and audio recordings up to 300%.',
    fullDesc: 'Increase the loudness of low-volume audio files, phone recordings, and lectures with soft saturation peak protection.',
    category: 'media',
    icon: 'Volume2',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['audio/mpeg', 'audio/wav', 'audio/aac', 'audio/ogg', 'audio/x-m4a', 'audio/flac'],
    acceptedExtensions: ['.mp3', '.wav', '.aac', '.ogg', '.m4a', '.flac'],
    maxFiles: 5,
    maxFileSizeMB: 500,
    outputExtension: 'wav',
    outputMimeType: 'audio/wav',
    tags: ['volume booster', 'audio boost', 'amplify audio', 'louder mp3', 'gain boost'],
  },
  {
    id: 'audio-speed',
    slug: 'audio-speed',
    name: 'Audio Speed & Tempo Changer',
    shortDesc: 'Speed up or slow down MP3 and WAV audio playback from 0.5x to 2.5x.',
    fullDesc: 'Change audio speed for language learning, fast lecture listening, or slow transcription without quality loss.',
    category: 'media',
    icon: 'FastForward',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['audio/mpeg', 'audio/wav', 'audio/aac', 'audio/ogg', 'audio/x-m4a', 'audio/flac'],
    acceptedExtensions: ['.mp3', '.wav', '.aac', '.ogg', '.m4a', '.flac'],
    maxFiles: 5,
    maxFileSizeMB: 500,
    outputExtension: 'wav',
    outputMimeType: 'audio/wav',
    tags: ['audio speed', 'tempo changer', 'speed up mp3', 'slow audio', 'pitch change'],
  },
  {
    id: 'image-palette',
    slug: 'image-palette',
    name: 'Image Color Palette Extractor',
    shortDesc: 'Extract dominant HEX, RGB color swatches and CSS palettes from images.',
    fullDesc: 'Upload logos, photos, and artwork to extract primary color harmonies and copy CSS variables instantly.',
    category: 'image',
    icon: 'Palette',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['image/jpeg', 'image/png', 'image/webp', 'image/svg+xml'],
    acceptedExtensions: ['.jpg', '.jpeg', '.png', '.webp', '.svg'],
    maxFiles: 1,
    maxFileSizeMB: 150,
    outputExtension: 'txt',
    outputMimeType: 'text/plain',
    tags: ['color palette', 'extract colors', 'hex codes', 'image colors', 'color picker'],
  },
  {
    id: 'pdf-organizer',
    slug: 'pdf-organizer',
    name: 'PDF Page Organizer & Reorder',
    shortDesc: 'Visually rearrange, rotate, and delete pages from PDF documents.',
    fullDesc: 'Interactive thumbnail grid to drag and drop page order, rotate individual pages, and remove unwanted pages.',
    category: 'pdf',
    icon: 'Layers',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['application/pdf'],
    acceptedExtensions: ['.pdf'],
    maxFiles: 1,
    maxFileSizeMB: 500,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    tags: ['reorder pdf', 'pdf organizer', 'delete pdf pages', 'rotate pages', 'arrange pdf'],
  },
  {
    id: 'markdown-editor',
    slug: 'markdown-editor',
    name: 'Live Markdown to PDF Studio',
    shortDesc: 'Write Markdown with real-time preview and export formatted PDF.',
    fullDesc: 'Split-screen live Markdown documentation editor with table formatting, code syntax highlighting, and 1-click PDF download.',
    category: 'dev',
    icon: 'FileCode',
    popular: true,
    featured: true,
    isClientSide: true,
    acceptedMimeTypes: ['text/markdown', 'text/plain'],
    acceptedExtensions: ['.md', '.txt'],
    maxFiles: 1,
    maxFileSizeMB: 10,
    outputExtension: 'pdf',
    outputMimeType: 'application/pdf',
    tags: ['markdown editor', 'md to pdf', 'live markdown', 'doc generator', 'markdown preview'],
  },
];

export const CATEGORIES_CONFIG: { id: ToolCategory; label: string; icon: string; desc: string }[] = [
  { id: 'media', label: 'Video & Media', icon: 'Video', desc: 'Download 4K videos & MP3 audio from YouTube, Reels, TikTok, FB & WhatsApp.' },
  { id: 'pdf', label: 'PDF Tools', icon: 'FileText', desc: 'Merge, split, compress, edit, secure and convert PDF documents.' },
  { id: 'image', label: 'Image Tools', icon: 'Image', desc: 'Convert, compress, crop, resize, and optimize pictures.' },
  { id: 'document', label: 'Document Tools', icon: 'FileCheck', desc: 'Convert Word, Excel, CSV, and Markdown files.' },
  { id: 'text', label: 'Text & Writing', icon: 'Type', desc: 'Word count, case converters, line sorters, and diff checker.' },
  { id: 'compress', label: 'Compression', icon: 'Minimize2', desc: 'Reduce file sizes of PDFs, images, and documents.' },
  { id: 'ocr', label: 'OCR Center', icon: 'ScanText', desc: 'Extract text from scanned PDFs and images in 7+ languages.' },
  { id: 'calculator', label: 'Calculators & Units', icon: 'Binary', desc: 'Storage units, bandwidth transfer ETA, general units, and ratios.' },
  { id: 'dev', label: 'Developer Utilities', icon: 'Code2', desc: 'JSON formatter, Base64, timestamps, colors, and minifiers.' },
  { id: 'security', label: 'Security & Hashes', icon: 'Fingerprint', desc: 'SHA-256 checksums, secure password generator, and strength meter.' },
  { id: 'qr', label: 'QR & Barcodes', icon: 'QrCode', desc: 'Generate styled QR codes and inventory barcodes.' },
  { id: 'ai', label: 'AI Workspace', icon: 'Sparkles', desc: 'AI document summarizer, rewriter, and grammar assistant.' },
];
